#version 450
#pragma shader_stage(compute)
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_GOOGLE_include_directive : enable

//
// The name of this shader is "shadows-caster" as in, "shadows" category, "caster" subtype.
//

layout (local_size_x = 64) in;

#include "../../includes/structs/rendered_mesh_cull_data.glsl"
#include "../../includes/structs/VkDrawIndexedIndirectCommand.glsl"

layout (constant_id = 0) const int MESH_COUNT     = 100;
layout (constant_id = 1) const int CASTER_COUNT   = 4;
layout (constant_id = 2) const int CURRENT_CASTER = 0;

layout(std430,set=0,binding = 0) readonly buffer MeshBuffer {
	rendered_mesh_cull_data scene_meshes[MESH_COUNT];
};
layout(std430,set=0,binding = 1) readonly buffer LightBuffer {
	vec4 active_casters[CASTER_COUNT]; // XYZ position and radius
};
layout(std430,set=0,binding = 2) readonly buffer ObjectIndexBuffer {
	int mesh_indices[MESH_COUNT];
};
layout(std430,set=0,binding = 3) writeonly buffer DrawCommandBuffer {
	VkDrawIndexedIndirectCommand indirect_draws[MESH_COUNT];
};

float get_scale(int mesh_index) {
	//
	// Assumes uniform scaling; for non-uniform scaling I'd have to figure out ellipse/plane tests 
	// and, for CPU-side stuff, line/ellipse intersection tests.
	//
	return length(vec3(scene_meshes[mesh_index].transform[0]));
}

void main() {
	uint draw_index = gl_GlobalInvocationID.x;
	if (draw_index >= MESH_COUNT)
		return;
	int mesh = mesh_indices[draw_index];
	if (mesh < 0) {
		//indirect_draws[draw_index].instanceCount = 0; // the CPU should already have done this
		return;
	}
	if ((scene_meshes[mesh].flags & RENDERED_MESH_CULL_FLAG_CULLED_BY_APPLICATION) != 0) {
		indirect_draws[draw_index].instanceCount = 0;
		return;
	}
	//
	vec3  pos       = scene_meshes[mesh].bounding_sphere_center;
	vec3  light_pos = active_casters[CURRENT_CASTER].xyz;
	float radius    = scene_meshes[mesh].bounding_sphere_radius;
	pos     = vec3(scene_meshes[mesh].transform * vec4(pos, 1));
	radius *= get_scale(mesh);
	if (length(pos - light_pos) <= radius + active_casters[CURRENT_CASTER].w) {
		indirect_draws[draw_index].instanceCount = 1;
	} else {
		indirect_draws[draw_index].instanceCount = 0;
	}
}