
#pragma push_macro("MACRO_LAST_N_OF")
#pragma push_macro("MACRO_EXPAND")
#define MACRO_LAST_N_OF(n, ...) MACRO_EXPAND(MACRO_LAST_##n##_OF(__VA_ARGS__))
#define MACRO_EXPAND(...) __VA_ARGS__

#include "./macro_first_n_of.h"

/*

Generated via JavaScript:

{
   let pushes = "";
   let out    = "";

   pushes += `#pragma push_macro("MACRO_LAST_0_OF")\n`;
   pushes += `#pragma push_macro("MACRO_LAST_1_OF")\n`;
   out += "#define MACRO_LAST_0_OF(...)\n";
   out += "#define MACRO_LAST_1_OF(x, y) y\n";

   for(let i = 2; i < 128; ++i) {
      pushes += `#pragma push_macro("MACRO_LAST_${i}_OF")\n`;

      let line = `#define MACRO_LAST_${i}_OF(x, ...) x,MACRO_FIRST_N_OF(${i - 1}, __VA_ARGS__)`;
      out += line + "\n";
   }
   pushes + "\n" + out;
}

*/

#pragma push_macro("MACRO_LAST_0_OF")
#pragma push_macro("MACRO_LAST_1_OF")
#pragma push_macro("MACRO_LAST_2_OF")
#pragma push_macro("MACRO_LAST_3_OF")
#pragma push_macro("MACRO_LAST_4_OF")
#pragma push_macro("MACRO_LAST_5_OF")
#pragma push_macro("MACRO_LAST_6_OF")
#pragma push_macro("MACRO_LAST_7_OF")
#pragma push_macro("MACRO_LAST_8_OF")
#pragma push_macro("MACRO_LAST_9_OF")
#pragma push_macro("MACRO_LAST_10_OF")
#pragma push_macro("MACRO_LAST_11_OF")
#pragma push_macro("MACRO_LAST_12_OF")
#pragma push_macro("MACRO_LAST_13_OF")
#pragma push_macro("MACRO_LAST_14_OF")
#pragma push_macro("MACRO_LAST_15_OF")
#pragma push_macro("MACRO_LAST_16_OF")
#pragma push_macro("MACRO_LAST_17_OF")
#pragma push_macro("MACRO_LAST_18_OF")
#pragma push_macro("MACRO_LAST_19_OF")
#pragma push_macro("MACRO_LAST_20_OF")
#pragma push_macro("MACRO_LAST_21_OF")
#pragma push_macro("MACRO_LAST_22_OF")
#pragma push_macro("MACRO_LAST_23_OF")
#pragma push_macro("MACRO_LAST_24_OF")
#pragma push_macro("MACRO_LAST_25_OF")
#pragma push_macro("MACRO_LAST_26_OF")
#pragma push_macro("MACRO_LAST_27_OF")
#pragma push_macro("MACRO_LAST_28_OF")
#pragma push_macro("MACRO_LAST_29_OF")
#pragma push_macro("MACRO_LAST_30_OF")
#pragma push_macro("MACRO_LAST_31_OF")
#pragma push_macro("MACRO_LAST_32_OF")
#pragma push_macro("MACRO_LAST_33_OF")
#pragma push_macro("MACRO_LAST_34_OF")
#pragma push_macro("MACRO_LAST_35_OF")
#pragma push_macro("MACRO_LAST_36_OF")
#pragma push_macro("MACRO_LAST_37_OF")
#pragma push_macro("MACRO_LAST_38_OF")
#pragma push_macro("MACRO_LAST_39_OF")
#pragma push_macro("MACRO_LAST_40_OF")
#pragma push_macro("MACRO_LAST_41_OF")
#pragma push_macro("MACRO_LAST_42_OF")
#pragma push_macro("MACRO_LAST_43_OF")
#pragma push_macro("MACRO_LAST_44_OF")
#pragma push_macro("MACRO_LAST_45_OF")
#pragma push_macro("MACRO_LAST_46_OF")
#pragma push_macro("MACRO_LAST_47_OF")
#pragma push_macro("MACRO_LAST_48_OF")
#pragma push_macro("MACRO_LAST_49_OF")
#pragma push_macro("MACRO_LAST_50_OF")
#pragma push_macro("MACRO_LAST_51_OF")
#pragma push_macro("MACRO_LAST_52_OF")
#pragma push_macro("MACRO_LAST_53_OF")
#pragma push_macro("MACRO_LAST_54_OF")
#pragma push_macro("MACRO_LAST_55_OF")
#pragma push_macro("MACRO_LAST_56_OF")
#pragma push_macro("MACRO_LAST_57_OF")
#pragma push_macro("MACRO_LAST_58_OF")
#pragma push_macro("MACRO_LAST_59_OF")
#pragma push_macro("MACRO_LAST_60_OF")
#pragma push_macro("MACRO_LAST_61_OF")
#pragma push_macro("MACRO_LAST_62_OF")
#pragma push_macro("MACRO_LAST_63_OF")
#pragma push_macro("MACRO_LAST_64_OF")
#pragma push_macro("MACRO_LAST_65_OF")
#pragma push_macro("MACRO_LAST_66_OF")
#pragma push_macro("MACRO_LAST_67_OF")
#pragma push_macro("MACRO_LAST_68_OF")
#pragma push_macro("MACRO_LAST_69_OF")
#pragma push_macro("MACRO_LAST_70_OF")
#pragma push_macro("MACRO_LAST_71_OF")
#pragma push_macro("MACRO_LAST_72_OF")
#pragma push_macro("MACRO_LAST_73_OF")
#pragma push_macro("MACRO_LAST_74_OF")
#pragma push_macro("MACRO_LAST_75_OF")
#pragma push_macro("MACRO_LAST_76_OF")
#pragma push_macro("MACRO_LAST_77_OF")
#pragma push_macro("MACRO_LAST_78_OF")
#pragma push_macro("MACRO_LAST_79_OF")
#pragma push_macro("MACRO_LAST_80_OF")
#pragma push_macro("MACRO_LAST_81_OF")
#pragma push_macro("MACRO_LAST_82_OF")
#pragma push_macro("MACRO_LAST_83_OF")
#pragma push_macro("MACRO_LAST_84_OF")
#pragma push_macro("MACRO_LAST_85_OF")
#pragma push_macro("MACRO_LAST_86_OF")
#pragma push_macro("MACRO_LAST_87_OF")
#pragma push_macro("MACRO_LAST_88_OF")
#pragma push_macro("MACRO_LAST_89_OF")
#pragma push_macro("MACRO_LAST_90_OF")
#pragma push_macro("MACRO_LAST_91_OF")
#pragma push_macro("MACRO_LAST_92_OF")
#pragma push_macro("MACRO_LAST_93_OF")
#pragma push_macro("MACRO_LAST_94_OF")
#pragma push_macro("MACRO_LAST_95_OF")
#pragma push_macro("MACRO_LAST_96_OF")
#pragma push_macro("MACRO_LAST_97_OF")
#pragma push_macro("MACRO_LAST_98_OF")
#pragma push_macro("MACRO_LAST_99_OF")
#pragma push_macro("MACRO_LAST_100_OF")
#pragma push_macro("MACRO_LAST_101_OF")
#pragma push_macro("MACRO_LAST_102_OF")
#pragma push_macro("MACRO_LAST_103_OF")
#pragma push_macro("MACRO_LAST_104_OF")
#pragma push_macro("MACRO_LAST_105_OF")
#pragma push_macro("MACRO_LAST_106_OF")
#pragma push_macro("MACRO_LAST_107_OF")
#pragma push_macro("MACRO_LAST_108_OF")
#pragma push_macro("MACRO_LAST_109_OF")
#pragma push_macro("MACRO_LAST_110_OF")
#pragma push_macro("MACRO_LAST_111_OF")
#pragma push_macro("MACRO_LAST_112_OF")
#pragma push_macro("MACRO_LAST_113_OF")
#pragma push_macro("MACRO_LAST_114_OF")
#pragma push_macro("MACRO_LAST_115_OF")
#pragma push_macro("MACRO_LAST_116_OF")
#pragma push_macro("MACRO_LAST_117_OF")
#pragma push_macro("MACRO_LAST_118_OF")
#pragma push_macro("MACRO_LAST_119_OF")
#pragma push_macro("MACRO_LAST_120_OF")
#pragma push_macro("MACRO_LAST_121_OF")
#pragma push_macro("MACRO_LAST_122_OF")
#pragma push_macro("MACRO_LAST_123_OF")
#pragma push_macro("MACRO_LAST_124_OF")
#pragma push_macro("MACRO_LAST_125_OF")
#pragma push_macro("MACRO_LAST_126_OF")
#pragma push_macro("MACRO_LAST_127_OF")

#define MACRO_LAST_0_OF(...)
#define MACRO_LAST_1_OF(x, y) y
#define MACRO_LAST_2_OF(x, ...) x,MACRO_FIRST_N_OF(1, __VA_ARGS__)
#define MACRO_LAST_3_OF(x, ...) x,MACRO_FIRST_N_OF(2, __VA_ARGS__)
#define MACRO_LAST_4_OF(x, ...) x,MACRO_FIRST_N_OF(3, __VA_ARGS__)
#define MACRO_LAST_5_OF(x, ...) x,MACRO_FIRST_N_OF(4, __VA_ARGS__)
#define MACRO_LAST_6_OF(x, ...) x,MACRO_FIRST_N_OF(5, __VA_ARGS__)
#define MACRO_LAST_7_OF(x, ...) x,MACRO_FIRST_N_OF(6, __VA_ARGS__)
#define MACRO_LAST_8_OF(x, ...) x,MACRO_FIRST_N_OF(7, __VA_ARGS__)
#define MACRO_LAST_9_OF(x, ...) x,MACRO_FIRST_N_OF(8, __VA_ARGS__)
#define MACRO_LAST_10_OF(x, ...) x,MACRO_FIRST_N_OF(9, __VA_ARGS__)
#define MACRO_LAST_11_OF(x, ...) x,MACRO_FIRST_N_OF(10, __VA_ARGS__)
#define MACRO_LAST_12_OF(x, ...) x,MACRO_FIRST_N_OF(11, __VA_ARGS__)
#define MACRO_LAST_13_OF(x, ...) x,MACRO_FIRST_N_OF(12, __VA_ARGS__)
#define MACRO_LAST_14_OF(x, ...) x,MACRO_FIRST_N_OF(13, __VA_ARGS__)
#define MACRO_LAST_15_OF(x, ...) x,MACRO_FIRST_N_OF(14, __VA_ARGS__)
#define MACRO_LAST_16_OF(x, ...) x,MACRO_FIRST_N_OF(15, __VA_ARGS__)
#define MACRO_LAST_17_OF(x, ...) x,MACRO_FIRST_N_OF(16, __VA_ARGS__)
#define MACRO_LAST_18_OF(x, ...) x,MACRO_FIRST_N_OF(17, __VA_ARGS__)
#define MACRO_LAST_19_OF(x, ...) x,MACRO_FIRST_N_OF(18, __VA_ARGS__)
#define MACRO_LAST_20_OF(x, ...) x,MACRO_FIRST_N_OF(19, __VA_ARGS__)
#define MACRO_LAST_21_OF(x, ...) x,MACRO_FIRST_N_OF(20, __VA_ARGS__)
#define MACRO_LAST_22_OF(x, ...) x,MACRO_FIRST_N_OF(21, __VA_ARGS__)
#define MACRO_LAST_23_OF(x, ...) x,MACRO_FIRST_N_OF(22, __VA_ARGS__)
#define MACRO_LAST_24_OF(x, ...) x,MACRO_FIRST_N_OF(23, __VA_ARGS__)
#define MACRO_LAST_25_OF(x, ...) x,MACRO_FIRST_N_OF(24, __VA_ARGS__)
#define MACRO_LAST_26_OF(x, ...) x,MACRO_FIRST_N_OF(25, __VA_ARGS__)
#define MACRO_LAST_27_OF(x, ...) x,MACRO_FIRST_N_OF(26, __VA_ARGS__)
#define MACRO_LAST_28_OF(x, ...) x,MACRO_FIRST_N_OF(27, __VA_ARGS__)
#define MACRO_LAST_29_OF(x, ...) x,MACRO_FIRST_N_OF(28, __VA_ARGS__)
#define MACRO_LAST_30_OF(x, ...) x,MACRO_FIRST_N_OF(29, __VA_ARGS__)
#define MACRO_LAST_31_OF(x, ...) x,MACRO_FIRST_N_OF(30, __VA_ARGS__)
#define MACRO_LAST_32_OF(x, ...) x,MACRO_FIRST_N_OF(31, __VA_ARGS__)
#define MACRO_LAST_33_OF(x, ...) x,MACRO_FIRST_N_OF(32, __VA_ARGS__)
#define MACRO_LAST_34_OF(x, ...) x,MACRO_FIRST_N_OF(33, __VA_ARGS__)
#define MACRO_LAST_35_OF(x, ...) x,MACRO_FIRST_N_OF(34, __VA_ARGS__)
#define MACRO_LAST_36_OF(x, ...) x,MACRO_FIRST_N_OF(35, __VA_ARGS__)
#define MACRO_LAST_37_OF(x, ...) x,MACRO_FIRST_N_OF(36, __VA_ARGS__)
#define MACRO_LAST_38_OF(x, ...) x,MACRO_FIRST_N_OF(37, __VA_ARGS__)
#define MACRO_LAST_39_OF(x, ...) x,MACRO_FIRST_N_OF(38, __VA_ARGS__)
#define MACRO_LAST_40_OF(x, ...) x,MACRO_FIRST_N_OF(39, __VA_ARGS__)
#define MACRO_LAST_41_OF(x, ...) x,MACRO_FIRST_N_OF(40, __VA_ARGS__)
#define MACRO_LAST_42_OF(x, ...) x,MACRO_FIRST_N_OF(41, __VA_ARGS__)
#define MACRO_LAST_43_OF(x, ...) x,MACRO_FIRST_N_OF(42, __VA_ARGS__)
#define MACRO_LAST_44_OF(x, ...) x,MACRO_FIRST_N_OF(43, __VA_ARGS__)
#define MACRO_LAST_45_OF(x, ...) x,MACRO_FIRST_N_OF(44, __VA_ARGS__)
#define MACRO_LAST_46_OF(x, ...) x,MACRO_FIRST_N_OF(45, __VA_ARGS__)
#define MACRO_LAST_47_OF(x, ...) x,MACRO_FIRST_N_OF(46, __VA_ARGS__)
#define MACRO_LAST_48_OF(x, ...) x,MACRO_FIRST_N_OF(47, __VA_ARGS__)
#define MACRO_LAST_49_OF(x, ...) x,MACRO_FIRST_N_OF(48, __VA_ARGS__)
#define MACRO_LAST_50_OF(x, ...) x,MACRO_FIRST_N_OF(49, __VA_ARGS__)
#define MACRO_LAST_51_OF(x, ...) x,MACRO_FIRST_N_OF(50, __VA_ARGS__)
#define MACRO_LAST_52_OF(x, ...) x,MACRO_FIRST_N_OF(51, __VA_ARGS__)
#define MACRO_LAST_53_OF(x, ...) x,MACRO_FIRST_N_OF(52, __VA_ARGS__)
#define MACRO_LAST_54_OF(x, ...) x,MACRO_FIRST_N_OF(53, __VA_ARGS__)
#define MACRO_LAST_55_OF(x, ...) x,MACRO_FIRST_N_OF(54, __VA_ARGS__)
#define MACRO_LAST_56_OF(x, ...) x,MACRO_FIRST_N_OF(55, __VA_ARGS__)
#define MACRO_LAST_57_OF(x, ...) x,MACRO_FIRST_N_OF(56, __VA_ARGS__)
#define MACRO_LAST_58_OF(x, ...) x,MACRO_FIRST_N_OF(57, __VA_ARGS__)
#define MACRO_LAST_59_OF(x, ...) x,MACRO_FIRST_N_OF(58, __VA_ARGS__)
#define MACRO_LAST_60_OF(x, ...) x,MACRO_FIRST_N_OF(59, __VA_ARGS__)
#define MACRO_LAST_61_OF(x, ...) x,MACRO_FIRST_N_OF(60, __VA_ARGS__)
#define MACRO_LAST_62_OF(x, ...) x,MACRO_FIRST_N_OF(61, __VA_ARGS__)
#define MACRO_LAST_63_OF(x, ...) x,MACRO_FIRST_N_OF(62, __VA_ARGS__)
#define MACRO_LAST_64_OF(x, ...) x,MACRO_FIRST_N_OF(63, __VA_ARGS__)
#define MACRO_LAST_65_OF(x, ...) x,MACRO_FIRST_N_OF(64, __VA_ARGS__)
#define MACRO_LAST_66_OF(x, ...) x,MACRO_FIRST_N_OF(65, __VA_ARGS__)
#define MACRO_LAST_67_OF(x, ...) x,MACRO_FIRST_N_OF(66, __VA_ARGS__)
#define MACRO_LAST_68_OF(x, ...) x,MACRO_FIRST_N_OF(67, __VA_ARGS__)
#define MACRO_LAST_69_OF(x, ...) x,MACRO_FIRST_N_OF(68, __VA_ARGS__)
#define MACRO_LAST_70_OF(x, ...) x,MACRO_FIRST_N_OF(69, __VA_ARGS__)
#define MACRO_LAST_71_OF(x, ...) x,MACRO_FIRST_N_OF(70, __VA_ARGS__)
#define MACRO_LAST_72_OF(x, ...) x,MACRO_FIRST_N_OF(71, __VA_ARGS__)
#define MACRO_LAST_73_OF(x, ...) x,MACRO_FIRST_N_OF(72, __VA_ARGS__)
#define MACRO_LAST_74_OF(x, ...) x,MACRO_FIRST_N_OF(73, __VA_ARGS__)
#define MACRO_LAST_75_OF(x, ...) x,MACRO_FIRST_N_OF(74, __VA_ARGS__)
#define MACRO_LAST_76_OF(x, ...) x,MACRO_FIRST_N_OF(75, __VA_ARGS__)
#define MACRO_LAST_77_OF(x, ...) x,MACRO_FIRST_N_OF(76, __VA_ARGS__)
#define MACRO_LAST_78_OF(x, ...) x,MACRO_FIRST_N_OF(77, __VA_ARGS__)
#define MACRO_LAST_79_OF(x, ...) x,MACRO_FIRST_N_OF(78, __VA_ARGS__)
#define MACRO_LAST_80_OF(x, ...) x,MACRO_FIRST_N_OF(79, __VA_ARGS__)
#define MACRO_LAST_81_OF(x, ...) x,MACRO_FIRST_N_OF(80, __VA_ARGS__)
#define MACRO_LAST_82_OF(x, ...) x,MACRO_FIRST_N_OF(81, __VA_ARGS__)
#define MACRO_LAST_83_OF(x, ...) x,MACRO_FIRST_N_OF(82, __VA_ARGS__)
#define MACRO_LAST_84_OF(x, ...) x,MACRO_FIRST_N_OF(83, __VA_ARGS__)
#define MACRO_LAST_85_OF(x, ...) x,MACRO_FIRST_N_OF(84, __VA_ARGS__)
#define MACRO_LAST_86_OF(x, ...) x,MACRO_FIRST_N_OF(85, __VA_ARGS__)
#define MACRO_LAST_87_OF(x, ...) x,MACRO_FIRST_N_OF(86, __VA_ARGS__)
#define MACRO_LAST_88_OF(x, ...) x,MACRO_FIRST_N_OF(87, __VA_ARGS__)
#define MACRO_LAST_89_OF(x, ...) x,MACRO_FIRST_N_OF(88, __VA_ARGS__)
#define MACRO_LAST_90_OF(x, ...) x,MACRO_FIRST_N_OF(89, __VA_ARGS__)
#define MACRO_LAST_91_OF(x, ...) x,MACRO_FIRST_N_OF(90, __VA_ARGS__)
#define MACRO_LAST_92_OF(x, ...) x,MACRO_FIRST_N_OF(91, __VA_ARGS__)
#define MACRO_LAST_93_OF(x, ...) x,MACRO_FIRST_N_OF(92, __VA_ARGS__)
#define MACRO_LAST_94_OF(x, ...) x,MACRO_FIRST_N_OF(93, __VA_ARGS__)
#define MACRO_LAST_95_OF(x, ...) x,MACRO_FIRST_N_OF(94, __VA_ARGS__)
#define MACRO_LAST_96_OF(x, ...) x,MACRO_FIRST_N_OF(95, __VA_ARGS__)
#define MACRO_LAST_97_OF(x, ...) x,MACRO_FIRST_N_OF(96, __VA_ARGS__)
#define MACRO_LAST_98_OF(x, ...) x,MACRO_FIRST_N_OF(97, __VA_ARGS__)
#define MACRO_LAST_99_OF(x, ...) x,MACRO_FIRST_N_OF(98, __VA_ARGS__)
#define MACRO_LAST_100_OF(x, ...) x,MACRO_FIRST_N_OF(99, __VA_ARGS__)
#define MACRO_LAST_101_OF(x, ...) x,MACRO_FIRST_N_OF(100, __VA_ARGS__)
#define MACRO_LAST_102_OF(x, ...) x,MACRO_FIRST_N_OF(101, __VA_ARGS__)
#define MACRO_LAST_103_OF(x, ...) x,MACRO_FIRST_N_OF(102, __VA_ARGS__)
#define MACRO_LAST_104_OF(x, ...) x,MACRO_FIRST_N_OF(103, __VA_ARGS__)
#define MACRO_LAST_105_OF(x, ...) x,MACRO_FIRST_N_OF(104, __VA_ARGS__)
#define MACRO_LAST_106_OF(x, ...) x,MACRO_FIRST_N_OF(105, __VA_ARGS__)
#define MACRO_LAST_107_OF(x, ...) x,MACRO_FIRST_N_OF(106, __VA_ARGS__)
#define MACRO_LAST_108_OF(x, ...) x,MACRO_FIRST_N_OF(107, __VA_ARGS__)
#define MACRO_LAST_109_OF(x, ...) x,MACRO_FIRST_N_OF(108, __VA_ARGS__)
#define MACRO_LAST_110_OF(x, ...) x,MACRO_FIRST_N_OF(109, __VA_ARGS__)
#define MACRO_LAST_111_OF(x, ...) x,MACRO_FIRST_N_OF(110, __VA_ARGS__)
#define MACRO_LAST_112_OF(x, ...) x,MACRO_FIRST_N_OF(111, __VA_ARGS__)
#define MACRO_LAST_113_OF(x, ...) x,MACRO_FIRST_N_OF(112, __VA_ARGS__)
#define MACRO_LAST_114_OF(x, ...) x,MACRO_FIRST_N_OF(113, __VA_ARGS__)
#define MACRO_LAST_115_OF(x, ...) x,MACRO_FIRST_N_OF(114, __VA_ARGS__)
#define MACRO_LAST_116_OF(x, ...) x,MACRO_FIRST_N_OF(115, __VA_ARGS__)
#define MACRO_LAST_117_OF(x, ...) x,MACRO_FIRST_N_OF(116, __VA_ARGS__)
#define MACRO_LAST_118_OF(x, ...) x,MACRO_FIRST_N_OF(117, __VA_ARGS__)
#define MACRO_LAST_119_OF(x, ...) x,MACRO_FIRST_N_OF(118, __VA_ARGS__)
#define MACRO_LAST_120_OF(x, ...) x,MACRO_FIRST_N_OF(119, __VA_ARGS__)
#define MACRO_LAST_121_OF(x, ...) x,MACRO_FIRST_N_OF(120, __VA_ARGS__)
#define MACRO_LAST_122_OF(x, ...) x,MACRO_FIRST_N_OF(121, __VA_ARGS__)
#define MACRO_LAST_123_OF(x, ...) x,MACRO_FIRST_N_OF(122, __VA_ARGS__)
#define MACRO_LAST_124_OF(x, ...) x,MACRO_FIRST_N_OF(123, __VA_ARGS__)
#define MACRO_LAST_125_OF(x, ...) x,MACRO_FIRST_N_OF(124, __VA_ARGS__)
#define MACRO_LAST_126_OF(x, ...) x,MACRO_FIRST_N_OF(125, __VA_ARGS__)
#define MACRO_LAST_127_OF(x, ...) x,MACRO_FIRST_N_OF(126, __VA_ARGS__)