#pragma once
#include "notice_code_t.h"

namespace dovah {
   struct notice_code {
      notice_code()       = delete;
      enum type : notice_code_t {
         none = 0x00000000,
         //
         load_order_would_overflow_into_lights       = 0x00000001,
         load_order_contains_light_files             = 0x00000002,
         load_order_is_invalid_somehow               = 0x00000003, // The operation you wish to perform is impossible, because the load order is already in an invalid state.
         unknown_form_type                           = 0x00000004,
         cannot_save_right_now                       = 0x00000005, // It is not safe to save right now, as a save or load operation is already in progress.
         no_filename_specified                       = 0x00000006,
         save_complete_but_reopen_failed             = 0x00000007, // A file was successfully saved, but could not be reopened afterwards. Further editing is not possible.
         out_of_memory                               = 0x00000008,
         zlib_memory_error                           = 0x00000009,
         zlib_buffer_error                           = 0x0000000A,
         forms_out_of_esl_form_id_range              = 0x0000000B, // One or more relevant forms is outside of the range of form IDs available to an ESL.
         file_has_too_many_dependencies              = 0x0000000C,
         no_active_file                              = 0x0000000D,
         save_complete_but_to_temporary_file         = 0x0000000E, // The file was saved successfully, but only to a temporary file. It was not possible to rename that temporary file to the desired filename.
         unsaved_form_cleanup_failed                 = 0x0000000F, // Some forms were not saved to the file, but could not be deleted from memory. It is not safe to continue this editing session.
         form_override_has_type_mismatch             = 0x00000010,
         form_override_has_armo_arma_mismatch        = 0x00000011,
         cell_flags_not_yet_found                    = 0x00000012, // CELL full load: a subrecord specific to interior or exterior cells was found before we discovered (by virtue of CELL/DATA) what type of cell this is.
         interior_cell_data_in_exterior_cell         = 0x00000013, // CELL full load: a subrecord specific to interior cells was found in a cell that is flagged as an exterior.
         exterior_cell_data_in_interior_cell         = 0x00000014, // CELL full load: a subrecord specific to exterior cells was found in a cell that is flagged as an interior.
         unrecognized_subrecord                      = 0x00000015, // FORM full load: a subrecord was unrecognized.
         form_reference_is_of_incorrect_type         = 0x00000016, // FORM full load: a (form_reference_t) ended up referring to a form of the wrong type.
         shout_has_wrong_word_count                  = 0x00000017, // SHOU full load: the shout has too many, or too few, words.
         package_event_dialogue_unrecognized_subrecord = 0x00000018, // Unrecognized subrecord inside of the object. The loader for this object blindly consumes subrecords until it finds an expected end; if the end is missing, then this will end badly!
         game_setting_record_is_nameless             = 0x00000019, // A GMST record had no EDID or an empty EDID.
         game_setting_record_is_misordered           = 0x0000001A, // A GMST record has its EDID record in the wrong place.
         subrecord_has_extra_content                 = 0x0000001B, // A subrecord has unexpected data at its end. (This is not emitted for most subrecords, but is explicitly checked for in special cases like the GMST loader.)
         game_setting_record_is_redundant            = 0x0000001C, // Multiple GMST records in the same file define the same setting but with different form IDs.
         game_setting_record_has_bad_form_id         = 0x0000001D, // A GMST record has an out-of-bounds or otherwise invalid form ID.
         game_setting_record_has_bad_type            = 0x0000001E, // A GMST record has an unrecognized name, and the name's type prefix is also unrecognized.
         game_setting_name_is_unrecognized           = 0x0000001F,
         form_id_unavailable_for_game_setting        = 0x00000020, // A game setting edit request failed because a form ID wasn't available for use.
         game_setting_edit_request_lacked_id         = 0x00000021, // A game setting edit request failed because it had no form ID.
         form_id_is_already_in_use                   = 0x00000022,
         form_id_is_reserved_for_other_process       = 0x00000023, // Cannot use the specified form ID. It is reserved for use by another process, such as form creation or form renumbering.
         cannot_load_right_now                       = 0x00000024, // It is not safe to load right now, as a save or load operation is already in progress.
         game_setting_record_has_no_data             = 0x00000025, // A GMST record had no DATA subrecord.
         game_setting_record_unreadable_data         = 0x00000026, // A GMST record's DATA subrecord could not be read. This can happen if the subrecord is too small.
         cannot_sever_references_to_target           = 0x00000027,
         game_setting_is_not_in_active_file          = 0x00000028, // Cannot renumber a GMST that doesn't originate from the active file.
         default_object_rejected_for_bad_type        = 0x00000029, // The loaded DefaultObjectManager won't let you use the specified form for the specified entry, as the form is of the wrong type.
         default_object_accepted_but_unknown         = 0x0000002A, // The loaded DefaultObjectManager has created the specified entry, but wants you to know that the entry isn't one that DovahKit's backend recognizes.
         singleton_form_is_redundantly_defined       = 0x0000002B, // A file contained multiple records for the same singleton form (e.g. multiple DOBJ records or multiple NAVI records).
         cannot_renumber_hardcoded_form              = 0x0000002C,
         form_is_not_defined_in_active_file          = 0x0000002D, // The desired operation can only be performed on forms that were originally defined in the active file.
         zero_is_not_an_allowed_form_id              = 0x0000002E, // The desired operation does not allow you to use zero as a form ID.
         cannot_load_all_users_of_this_form          = 0x0000002F, // The desired operation requires that DovahKit load all of the forms that use the target form, and that isn't yet implemented.
         form_id_is_in_the_hardcoded_range           = 0x00000030, // You cannot use this form ID, because it's in the range reserved for hardcoded forms.
         cannot_sever_references_to_none_stub        = 0x00000031,
         unimplemented_form_type                     = 0x00000032, // DovahKit recognizes this form type and it is valid, but editing has not yet been implemented for it.
         invalid_parent_child_relationship           = 0x00000033, // Forms of type A cannot have parents of type B.
         exterior_grid_coordinates_already_taken     = 0x00000034, // Cannot create a cell with the specified coordinates, as a cell in this worldspace already has those coordinates.
         cannot_create_reference_with_no_parent_cell = 0x00000035,
         interior_cell_clone_cannot_have_parent      = 0x00000036, // When duplicating an interior cell, you must not specify a parent worldspace.
         exterior_cell_clone_must_have_parent        = 0x00000037, // When duplicating an exterior cell, you must specify a parent worldspace.
         form_created_but_clone_failed               = 0x00000038, // We were able to make a new form, but Form::clone() returned false; we made a blank new form instead of duplicating a form as requested.
         form_id_unavailable_for_new_form            = 0x00000039, // A form creation request failed because a form ID wasn't available for use.
         form_id_is_out_of_bounds                    = 0x0000003A, // The requested form ID is out-of-bounds, e.g. form ID 0x05000000 in a load order with fewer than six files.
         post_save_none_stub_cleanup_failed          = 0x0000003B, // Failed to clean up none-stubs after an otherwise successful save operation. It is not safe to continue this editing session.
         malformed_file                              = 0x0000003C, // Generic error code for malformed files.
         missing_master                              = 0x0000003D, // Failed to load a file, because one of the file's masters is missing.
         missing_file                                = 0x0000003E, // Failed to load a file, because the file is missing.
         locked_file                                 = 0x0000003F, // DovahKit was unable to read a file because it is locked by the OS.
         cyclical_dependency_between_files           = 0x00000040, // The load order contains files whose master lists form a circular dependency.
         active_file_is_master_and_there_are_plugins = 0x00000041, // DovahKit can't place the active file at the end of the load order, because it's ESM-flagged and other files aren't.
         record_found_in_wrong_top_level_group       = 0x00000042,
         cannot_inject_form_overtop_none_stub        = 0x00000043,
         container_item_has_bad_owner_form_type      = 0x00000044, // An item in a container is not owned by an NPC_ or a FACT.
         unknown_error                               = 0x00000045,
         active_file_is_dependency                   = 0x00000046, // The active file is listed as another file's master. This load order is invalid, because we need the active file at the bottom of the load order.
         load_order_would_have_too_many_files        = 0x00000047, // We can't load this load order. It would have too many files (greater than 4096 lights, 255 heavies, or if an active file is selected, 255 or 254 total).
         filesystem_error                            = 0x00000048,
         interior_cell_block_has_no_parent_group     = 0x00000049, // Malformed file: an interior cell block GRUP has no parent GRUP.
         interior_cell_block_group_badly_nested      = 0x0000004A, // Malformed file: an interior cell block GRUP is nested under a parent GRUP of the wrong type or hierarchy.
         invalid_record_signature                    = 0x0000004B, // Malformed file: a record had a suspicious (or just unknown) signature.
         form_id_is_inside_of_a_missing_master       = 0x0000004C,
         unexpected_nested_group_in_simple_top_group = 0x0000004D, // Malformed file: a "simple" top-level GRUP contained a nested GRUP.
         extended_subrecord_with_no_length           = 0x0000004E, // Malformed file: an 'XXXX' subrecord contained no usable length value.
         form_initial_record_is_partial              = 0x0000004F, // A form's initial record is flagged as "partial." The flag will not be honored when loading form data on-demand.
         form_initial_record_is_partial_and_injected = 0x00000050, // A form's initial record is flagged as "partial," and is injected. The game would skip this record entirely, so we're skipping it as well; the form has not been loaded.
         cannot_delete_hardcoded_form                = 0x00000051,
         quest_objective_unexpected_subrecord        = 0x00000052, // Unrecognized subrecord inside of the object. The loader for this object blindly consumes subrecords until it finds an expected end; if the end is missing, then this will end badly!
         parent_form_is_missing                      = 0x00000053, // Failed to load a file, because a form's parent form ID doesn't correspond to a valid form.
         partial_info_override_has_different_parent  = 0x00000054, // A partial-flagged INFO override has a different parent from the original. This can lead to all sorts of data mishandling in-game.
         dialogue_branch_mishandled_owning_quest_id  = 0x00000055, // A bug in the game's loader will cause it to mishandle this DLBR/QNAM subrecord.
         worldspace_is_its_own_parent                = 0x00000056, // A worldspace has been set to use itself as the parent world. The game will enter an infinite loading screen when trying to load it.
         quest_fragment_belongs_to_missing_log_entry = 0x00000057,
         too_many_script_fragments_to_save           = 0x00000058, // A form has too many script fragments, and cannot be saved.
         too_many_aliases_with_scripts_to_save       = 0x00000059, // A quest has too many aliases with script data, and cannot be saved.
         alias_papyrus_data_specifies_wrong_quest    = 0x0000005A, // An alias's Papyrus data was skipped because it claims to belong to a quest other than the containing quest.
         alias_papyrus_data_belongs_to_missing_alias = 0x0000005B, // A quest's VMAD subrecord supplied Papyrus data for an alias that doesn't actually exist.
         info_response_subrecord_before_responses    = 0x0000005C, // An INFO contains LNAM or SNAM subrecords outside of any response.
         attack_data_expected_event_subrecord        = 0x0000005D, // An ATKR subrecord was not followed by an ATKE subrecord; it will "eat" the next subrecord and assume it's ATKE.
         the_game_doesnt_load_new_actor_value_infos  = 0x0000005E, // Skyrim doesn't load new AVIF records. AVIF records that don't override a hardcoded AVIF form will be ignored.
         non_texture_note_includes_texture_path      = 0x0000005F, // A NOTE form included an XNAM subrecord but is not a texture note.
         length_prefixed_string_was_too_long_to_save = 0x00000060,
         too_many_destruction_stages_to_save         = 0x00000061,
         papyrus_property_has_multiple_scalar_values = 0x00000062, // Cannot save a non-array Papyrus property when it has multiple values in-memory. Something edited the property incorrectly.
         papyrus_property_is_scalar_but_empty        = 0x00000063, // Attempted to save a non-array Papyrus property that had no value. Something edited the property incorrectly. We saved it with a default.
         invalid_landscape_quad_index                = 0x00000064, // LAND full load: something tried to specify an out-of-bounds quad.
         landscape_quads_can_only_have_six_layers    = 0x00000065, // LAND full load: a landscape quad can only have six layers; higher layers overwrite the sixth at run-time.
         havok_data_is_not_supported_here            = 0x00000066, // This feature can't load/save/etc. Havok data.
         landscape_heights_are_too_steep             = 0x00000067, // This landscape cannot be saved, because there is too steep a slope somewhere in its heightmap.
         cannot_set_position_of_orphaned_reference   = 0x00000068, // This REFR has no parent (e.g. PlayerRef) and so cannot be moved.
         desired_position_is_outside_of_desired_cell = 0x00000069, // You asked to move this REFR to an exterior cell, but the position you wanted to use is outside of that cell's bounds.
         failed_to_create_cell_to_move_reference_to  = 0x0000006A, // The coordinates you wanted to move this REFR to lie outside of any existing cells, and attempting to create a new cell failed (e.g. no form ID available).
         cannot_reparent_hardcoded_reference         = 0x0000006B, // Hardcoded references typically don't exist in a parent cell, and cannot be reparented.
      };
   };
}
