#include "get_default_object_info.h"
#include <array>
#include <QObject>
#include <QString>

namespace {
   const char* dis_n = "DOBJ name";
   const char* dis_d = "DOBJ description";

   struct _info {
      uint32_t signature = 0;
      QString  name;
      QString  description;

      _info(uint32_t s, const QString& n, const QString& d) : signature(s), name(n), description(d) {}
      _info(uint32_t s, const QString& n) : signature(s), name(n) {}
   };
   std::array _default_objects = {
      _info('AAAC', QObject::tr("Action Activate", dis_n)),
      _info('AAB1', QObject::tr("Action Bleedout Start", dis_n)),
      _info('AAB2', QObject::tr("Action Bleedout Stop", dis_n)),
      _info('AABA', QObject::tr("Action Block Anticipate", dis_n)),
      _info('AABH', QObject::tr("Action Block Hit", dis_n)),
      _info('AABI', QObject::tr("Action Bumped Into", dis_n)),
      _info('AADA', QObject::tr("Action DualAttack", dis_n)),
      _info('AADE', QObject::tr("Action Death", dis_n)),
      _info('AADL', QObject::tr("Action DualRelease", dis_n)),
      _info('AADR', QObject::tr("Action Draw", dis_n)),
      _info('AADW', QObject::tr("Action Death Wait", dis_n)),
      _info('AAF1', QObject::tr("Action Fly Start", dis_n)),
      _info('AAF2', QObject::tr("Action Fly Stop", dis_n)),
      _info('AAFA', QObject::tr("Action Fall", dis_n)),
      _info('AAFQ', QObject::tr("Action Force Equip", dis_n)),
      _info('AAGU', QObject::tr("Action Get Up", dis_n)),
      _info('AAH1', QObject::tr("Action Hover Start", dis_n)),
      _info('AAH2', QObject::tr("Action Hover Stop", dis_n)),
      _info('AAID', QObject::tr("Action Idle", dis_n)),
      _info('AAIS', QObject::tr("Action Idle Stop", dis_n)),
      _info('AAJP', QObject::tr("Action Jump", dis_n)),
      _info('AALA', QObject::tr("Action LeftAttack", dis_n)),
      _info('AALD', QObject::tr("Action LeftReady", dis_n)),
      _info('AALI', QObject::tr("Action LeftInterrupt", dis_n)),
      _info('AALK', QObject::tr("Action Look", dis_n)),
      _info('AALM', QObject::tr("Action Large Movement Delta", dis_n)),
      _info('AALN', QObject::tr("Action Land", dis_n)),
      _info('AALR', QObject::tr("Action LeftRelease", dis_n)),
      _info('AAPA', QObject::tr("Action Right Power Attack", dis_n)),
      _info('AAPE', QObject::tr("Action Path End", dis_n)),
      _info('AAPS', QObject::tr("Action Path Start", dis_n)),
      _info('AAR2', QObject::tr("Action Large Recoil", dis_n)),
      _info('AARA', QObject::tr("Action RightAttack", dis_n)),
      _info('AARC', QObject::tr("Action Recoil", dis_n)),
      _info('AARD', QObject::tr("Action RightReady", dis_n)),
      _info('AARI', QObject::tr("Action RightInterrupt", dis_n)),
      _info('AARR', QObject::tr("Action RightRelease", dis_n)),
      _info('AAS1', QObject::tr("Action Stagger Start", dis_n)),
      _info('AASC', QObject::tr("Action Shield Change", dis_n)),
      _info('AASH', QObject::tr("Action Sheath", dis_n)),
      _info('AASN', QObject::tr("Action Sneak", dis_n)),
      _info('AASP', QObject::tr("Action Sprint Stop", dis_n)),
      _info('AASS', QObject::tr("Action Summoned Start", dis_n)),
      _info('AAST', QObject::tr("Action Sprint Start", dis_n)),
      _info('AASW', QObject::tr("Action Swim State Change", dis_n)),
      _info('AAVC', QObject::tr("Action Voice", dis_n)),
      _info('AAVD', QObject::tr("Action VoiceReady", dis_n)),
      _info('AAVI', QObject::tr("Action VoiceInterrupt", dis_n)),
      _info('AAVR', QObject::tr("Action VoiceRelease", dis_n)),
      _info('AAWH', QObject::tr("Action Ward Hit", dis_n)),
      _info('ABSE', QObject::tr("Art Object - Absorb Effect", dis_n), QObject::tr("An art-object spawned on actors and anchored to their bodies when they absorb an incoming spell. It will be pointed roughly toward the direction the spell came from, and will persist for fMagicAbsorbVisualTimer seconds.", dis_d)),
      _info('ADPA', QObject::tr("Action Dual Power Attack", dis_n)),
      _info('AFNP', QObject::tr("Keyword - Activator Furniture No Player", dis_n), QObject::tr("A keyword. If present on a furniture, then the player-character will be unable to enter the furniture.", dis_d)),
      _info('AHBM', QObject::tr("Keyword - Armor Material Heavy Bonemold", dis_n)),
      _info('AHCH', QObject::tr("Keyword - Armor Material Heavy Chitin", dis_n)),
      _info('AHNC', QObject::tr("Keyword - Armor Material Heavy Nordic", dis_n)),
      _info('AHSM', QObject::tr("Keyword - Armor Material Heavy Stalhrim", dis_n)),
      _info('AIDW', QObject::tr("Action Idle Warn", dis_n)),
      _info('AIVC', QObject::tr("Verlet Cape", dis_n), QObject::tr("A single armor item that should have \"verlet\" soft-body physics enabled for it. This is a special-case added for the Dawnguard DLC's Vampire Lord cape.", dis_d)),
      _info('AKDN', QObject::tr("Action Knockdown", dis_n)),
      _info('ALBM', QObject::tr("Keyword - Armor Material Light Bonemold", dis_n)),
      _info('ALCH', QObject::tr("Keyword - Armor Material Light Chitin", dis_n)),
      _info('ALDM', QObject::tr("Ash LOD Material", dis_n)),
      _info('ALHD', QObject::tr("Ash LOD Material (HD)", dis_n)),
      _info('ALNC', QObject::tr("Keyword - Armor Material Light Nordic", dis_n)),
      _info('ALPA', QObject::tr("Action Left Power Attack", dis_n)),
      _info('ALSM', QObject::tr("Keyword - Armor Material Light Stalhrim", dis_n)),
      _info('ALTI', QObject::tr("Action Listen Idle", dis_n)),
      _info('AMBK', QObject::tr("Action Move Backward", dis_n)),
      _info('AMFD', QObject::tr("Action Move Forward", dis_n)),
      _info('AMLT', QObject::tr("Action Move Left", dis_n)),
      _info('AMRT', QObject::tr("Action Move Right", dis_n)),
      _info('AMSP', QObject::tr("Action Move Stop", dis_n)),
      _info('AMST', QObject::tr("Action Move Start", dis_n)),
      _info('ANML', QObject::tr("Keyword - Animal", dis_n)),
      _info('AODA', QObject::tr("Keyword - Armor Material Daedric", dis_n)),
      _info('AODB', QObject::tr("Keyword - Armor Material Dragonbone", dis_n)),
      _info('AODP', QObject::tr("Keyword - Armor Material Dragonplate", dis_n)),
      _info('AODS', QObject::tr("Keyword - Armor Material Dragonscale", dis_n)),
      _info('AODW', QObject::tr("Keyword - Armor Material Dwarven", dis_n)),
      _info('AOEB', QObject::tr("Keyword - Armor Material Ebony", dis_n)),
      _info('AOEL', QObject::tr("Keyword - Armor Material Elven", dis_n)),
      _info('AOES', QObject::tr("Keyword - Armor Material ElvenSplinted", dis_n)),
      _info('AOFE', QObject::tr("Keyword - Armor Material Iron", dis_n)),
      _info('AOFL', QObject::tr("Keyword - Armor Material FullLeather", dis_n)),
      _info('AOGL', QObject::tr("Keyword - Armor Material Glass", dis_n)),
      _info('AOHI', QObject::tr("Keyword - Armor Material Hide", dis_n)),
      _info('AOIB', QObject::tr("Keyword - Armor Material IronBanded", dis_n)),
      _info('AOIH', QObject::tr("Keyword - Armor Material ImperialHeavy", dis_n)),
      _info('AOIM', QObject::tr("Keyword - Armor Material Imperial", dis_n)),
      _info('AOIR', QObject::tr("Keyword - Armor Material ImperialReinforced", dis_n)),
      _info('AOOR', QObject::tr("Keyword - Armor Material Orcish", dis_n)),
      _info('AOSC', QObject::tr("Keyword - Armor Material Scaled", dis_n)),
      _info('AOSD', QObject::tr("Keyword - Armor Material Studded", dis_n)),
      _info('AOSK', QObject::tr("Keyword - Armor Material Stormcloak", dis_n)),
      _info('AOSP', QObject::tr("Keyword - Armor Material SteelPlate", dis_n)),
      _info('AOST', QObject::tr("Keyword - Armor Material Steel", dis_n)),
      _info('APSH', QObject::tr("Allow Player Shout", dis_n)),
      _info('ARAG', QObject::tr("Action Reset Animation Graph", dis_n)),
      _info('AREL', QObject::tr("Action Reload", dis_n)),
      _info('ARGI', QObject::tr("Action Ragdoll Instant", dis_n)),
      _info('ARTL', QObject::tr("Armor Material List", dis_n)),
      _info('ASID', QObject::tr("Action Idle Stop Instant", dis_n)),
      _info('ATKI', QObject::tr("Action Talking Idle", dis_n)),
      _info('ATLE', QObject::tr("Action Turn Left", dis_n)),
      _info('ATRI', QObject::tr("Action Turn Right", dis_n)),
      _info('ATSP', QObject::tr("Action Turn Stop", dis_n)),
      _info('AVVP', QObject::tr("Vampire Available Perks", dis_n), QObject::tr("The global variable used to track how many points the player has available to spend on perks in Dawnguard's vampire perk tree.", dis_d)),
      _info('AVWP', QObject::tr("Werewolf Available Perks", dis_n), QObject::tr("The global variable used to track how many points the player has available to spend on perks in Dawnguard's werewolf perk tree.", dis_d)),
      _info('AWWS', QObject::tr("Action Waterwalk Start", dis_n)),
      _info('AWWW', QObject::tr("Bunny Faction", dis_n), QObject::tr("A Faction to which all bunnies and hares should belong. Used to help manage the \"Bunnies Slaughtered\" misc stat.", dis_d)),
      _info('BAPO', QObject::tr("Base Potion", dis_n), QObject::tr("The base form used as a template for player-created potions.", dis_d)),
      _info('BAPS', QObject::tr("Base Poison", dis_n), QObject::tr("The base form used as a template for player-created poisons.", dis_d)),
      _info('BEEP', QObject::tr("Keyword - Robot", dis_n)),
      _info('BENA', QObject::tr("Base Armor Enchantment", dis_n)),
      _info('BENW', QObject::tr("Base Weapon Enchantment", dis_n)),
      _info('BTMS', QObject::tr("Battle Music", dis_n)),
      _info('CACA', QObject::tr("Commanded Actor Ability", dis_n)),
      _info('CMPX', QObject::tr("Complex Scene Object", dis_n), QObject::tr("The base form to be used for \"complex scene markers,\" intended to be placed at specific points in the game world to signal performance-heavy areas to the game engine. The game keeps track of how many references with this base form exist in attached cells, and will alter hardcoded behaviors based on their presence or absence. Notably, the game doesn't care whether these references are enabled or disabled.", dis_d)),
      _info('COEX', QObject::tr("Keyword - Conditional Explosion", dis_n)),
      _info('COOK', QObject::tr("Keyword: Cooking Pot", dis_n), QObject::tr("Workbenches with this keyword are treated as cooking pots. The keyword is used to decide which tutorial message to display to the player.", dis_d)),
      _info('CSTY', QObject::tr("Combat Style", dis_n)),
      _info('CWNE', QObject::tr("Keyword - Civil War Neutral", dis_n)),
      _info('CWOK', QObject::tr("Keyword - Civil War Owner", dis_n)),
      _info('DAED', QObject::tr("Keyword - Daedra", dis_n)),
      _info('DBHF', QObject::tr("Dark Brotherhood Faction", dis_n)),
      _info('DCMS', QObject::tr("Dungeon Cleared Music", dis_n), QObject::tr("A music cue played when a location is cleared, if the location has the \"ClearableLocation\" keyword.", dis_d)),
      _info('DCZM', QObject::tr("Dragon Crash Zone Marker", dis_n)),
      _info('DDSC', QObject::tr("Dialogue Voice Category", dis_n)),
      _info('DEIS', QObject::tr("Drug Wears Off Image Space", dis_n), QObject::tr("An imagespace modifier that is activated when one of the player's active effects expires, if that effect came from a potion that is defined as having an addiction. Skyrim's data structures still have fields for Fallout 3-style chem additions, but as of this writing it's unclear how much of the functionality still works.", dis_d)),
      _info('DFMS', QObject::tr("Default Music", dis_n)),
      _info('DFTS', QObject::tr("Footstep Set", dis_n)),
      _info('DGFL', QObject::tr("DialogueFollower Quest", dis_n)),
      _info('DIEN', QObject::tr("Keyword - Disallow Enchanting", dis_n)),
      _info('DLMT', QObject::tr("Default Landscape Material Type", dis_n), QObject::tr("The physics material type used for any unpainted heightmapped terrain. Should be a dirt material, as unpainted terrain defaults to the \"Dirt02.dds\" and \"Dirt02_N.dds\" texture files.", dis_d)),
      _info('DLZM', QObject::tr("Dragon Land Zone Marker", dis_n)),
      _info('DMFL', QObject::tr("Default MovementType: Fly", dis_n)),
      _info('DMRN', QObject::tr("Default MovementType: Run", dis_n)),
      _info('DMSN', QObject::tr("Default MovementType: Sneak", dis_n)),
      _info('DMSP', QObject::tr("Default MovementType: Sprint", dis_n)),
      _info('DMSW', QObject::tr("Default MovementType: Swim", dis_n)),
      _info('DMWL', QObject::tr("Default MovementType: Walk", dis_n)),
      _info('DMXL', QObject::tr("Dragon Mount No Land List", dis_n)),
      _info('DOP2', QObject::tr("Dialogue Output Model (3D)", dis_n)),
      _info('DOP3', QObject::tr("Dialogue Output Model (2D)", dis_n)),
      _info('DRAK', QObject::tr("Keyword - Dragon", dis_n)),
      _info('DTMS', QObject::tr("Death Music", dis_n)),
      _info('EACA', QObject::tr("Every Actor Ability", dis_n)),
      _info('EHEQ', QObject::tr("EitherHand Equip", dis_n)),
      _info('EPDF', QObject::tr("Eat Package Default Food", dis_n), QObject::tr("The FormList used to define acceptable food items for any \"Eat\" AI procedure that doesn't specify its own FormList of food.", dis_d)),
      _info('FFFP', QObject::tr("Keyword - Furniture Forces 1st Person", dis_n), QObject::tr("Furniture with this keyword will force the player into first-person view when they use it.", dis_d)),
      _info('FFTP', QObject::tr("Keyword - Furniture Forces 3rd Person", dis_n), QObject::tr("Furniture with this keyword will force the player into third-person view when they use it.", dis_d)),
      _info('FGPD', QObject::tr("Favor Gifts Per Day", dis_n)),
      _info('FMFF', QObject::tr("Flying Mount - Fly Fast Worldspaces", dis_n)),
      _info('FMNS', QObject::tr("Flying Mount - Disallowed Spells", dis_n)),
      _info('FMYS', QObject::tr("Flying Mount - Allowed Spells", dis_n)),
      _info('FORG', QObject::tr("Keyword: Forge", dis_n), QObject::tr("Workbenches with this keyword are treated as blacksmith forges. The keyword is used to decide which tutorial message to display to the player.", dis_d)),
      _info('FPCL', QObject::tr("Favor Cost Large", dis_n)),
      _info('FPCM', QObject::tr("Favor Cost Medium", dis_n)),
      _info('FPCS', QObject::tr("Favor Cost Small", dis_n)),
      _info('FTEL', QObject::tr("Male Face Texture Set: Eyes", dis_n)),
      _info('FTGF', QObject::tr("Fighters' Guild Faction", dis_n)),
      _info('FTHD', QObject::tr("Male Face Texture Set: Head", dis_n)),
      _info('FTHF', QObject::tr("Female Face Texture Set: Head", dis_n)),
      _info('FTMF', QObject::tr("Female Face Texture Set: Mouth", dis_n)),
      _info('FTML', QObject::tr("Favor travel marker location", dis_n)),
      _info('FTMO', QObject::tr("Male Face Texture Set: Mouth", dis_n)),
      _info('FTNP', QObject::tr("Furniture Test NPC", dis_n), QObject::tr("The base form spawned by the PlaceFurnitureTester console command to serve as a test NPC. Non-ActorBase forms will produce warnings in-game.", dis_d)),
      _info('FTRF', QObject::tr("Female Face Texture Set: Eyes", dis_n)),
      _info('GCK1', QObject::tr("Keyword - Generic Craftable Keyword 01", dis_n)),
      _info('GCK2', QObject::tr("Keyword - Generic Craftable Keyword 02", dis_n)),
      _info('GCK3', QObject::tr("Keyword - Generic Craftable Keyword 03", dis_n)),
      _info('GCK4', QObject::tr("Keyword - Generic Craftable Keyword 04", dis_n)),
      _info('GCK5', QObject::tr("Keyword - Generic Craftable Keyword 05", dis_n)),
      _info('GCK6', QObject::tr("Keyword - Generic Craftable Keyword 06", dis_n)),
      _info('GCK7', QObject::tr("Keyword - Generic Craftable Keyword 07", dis_n)),
      _info('GCK8', QObject::tr("Keyword - Generic Craftable Keyword 08", dis_n)),
      _info('GCK9', QObject::tr("Keyword - Generic Craftable Keyword 09", dis_n)),
      _info('GCKX', QObject::tr("Keyword - Generic Craftable Keyword 10", dis_n)),
      _info('GFAC', QObject::tr("Guard Faction", dis_n)),
      _info('GOLD', QObject::tr("Gold", dis_n), QObject::tr("The MiscObject that the game will use as currency.", dis_d)),
      _info('HBAL', QObject::tr("Help - Basic Alchemy", dis_n)),
      _info('HBAT', QObject::tr("Help - Attack Target", dis_n)),
      _info('HBBR', QObject::tr("Help - Barter", dis_n)),
      _info('HBCO', QObject::tr("Help - Basic Cooking", dis_n)),
      _info('HBEC', QObject::tr("Help - Basic Enchanting", dis_n)),
      _info('HBFG', QObject::tr("Help - Basic Forging", dis_n)),
      _info('HBFM', QObject::tr("Help - Flying Mount", dis_n)),
      _info('HBFS', QObject::tr("Help - Favorites", dis_n)),
      _info('HBFT', QObject::tr("Help - Teamate Favor", dis_n)),
      _info('HBHJ', QObject::tr("Help - Jail", dis_n)),
      _info('HBJL', QObject::tr("Help - Journal", dis_n)),
      _info('HBLH', QObject::tr("Help - Low Health", dis_n)),
      _info('HBLK', QObject::tr("Help - Basic Lockpicking (PC)", dis_n)),
      _info('HBLM', QObject::tr("Help - Low Magicka", dis_n)),
      _info('HBLS', QObject::tr("Help - Low Stamina", dis_n)),
      _info('HBLU', QObject::tr("Help - Leveling up", dis_n)),
      _info('HBLX', QObject::tr("Help - Basic Lockpicking (Console)", dis_n)),
      _info('HBML', QObject::tr("Help - Basic Smelting", dis_n)),
      _info('HBMM', QObject::tr("Help - Map Menu", dis_n)),
      _info('HBOC', QObject::tr("Help - Basic Object Creation", dis_n)),
      _info('HBSA', QObject::tr("Help - Basic Smithing Armor", dis_n)),
      _info('HBSK', QObject::tr("Help - Skills Menu", dis_n)),
      _info('HBSM', QObject::tr("Help - Basic Smithing Weapon", dis_n)),
      _info('HBTA', QObject::tr("Help - Basic Tanning", dis_n)),
      _info('HBTL', QObject::tr("Help - Target Lock", dis_n)),
      _info('HBWC', QObject::tr("Help - Weapon Charge", dis_n)),
      _info('HCLL', QObject::tr("FormList - Hair Color List", dis_n)),
      _info('HFSD', QObject::tr("Heartbeat Sound Fast", dis_n)),
      _info('HMPC', QObject::tr("Help Manual PC", dis_n)),
      _info('HMXB', QObject::tr("Help Manual XBox", dis_n)),
      _info('HRSK', QObject::tr("Keyword - Horse", dis_n)),
      _info('HSSD', QObject::tr("Heartbeat Sound Slow", dis_n)),
      _info('HVFS', QObject::tr("Harvest Failed Sound", dis_n)),
      _info('HVSS', QObject::tr("Harvest Sound", dis_n), QObject::tr("Sound played when the player harvests flora, if the harvested object is of a type that can't define pickup/put-down sounds.", dis_d)),
      _info('IMID', QObject::tr("ImageSpaceModifier for inventory menu.", dis_n)),
      _info('IMLH', QObject::tr("Imagespace: Low Health", dis_n)),
      _info('INVP', QObject::tr("Inventory Player", dis_n)),
      _info('IOPM', QObject::tr("Interface Output Model", dis_n)),
      _info('JRLF', QObject::tr("Jarl Faction", dis_n)),
      _info('JWLR', QObject::tr("Keyword - Jewelry", dis_n)),
      _info('KHFL', QObject::tr("Kinect Help FormList", dis_n)),
      _info('KWBR', QObject::tr("Keyword - BeastRace", dis_n), QObject::tr("A keyword that can be set on a race. Its uses include managing the IsBeastRace variable in actors' animation graphs.", dis_d)),
      _info('KWCU', QObject::tr("Keyword - Cuirass", dis_n)),
      _info('KWDM', QObject::tr("Keyword - DummyObject", dis_n)),
      _info('KWDO', QObject::tr("Keyword - ClearableLocation", dis_n), QObject::tr("Used to determine whether a location should play a music cue when cleared, and whether a \"Cleared\" tag should be visible on the map.", dis_d)),
      _info('KWGE', QObject::tr("Keyword - UseGeometryEmitter", dis_n)),
      _info('KWMS', QObject::tr("Keyword - MustStop", dis_n)),
      _info('KWOT', QObject::tr("Keyword - Skip Outfit Items", dis_n)),
      _info('KWSP', QObject::tr("Skyrim - Worldspace", dis_n), QObject::tr("Used to tell the UI which of the game's worldspaces is Skyrim; apparently signals to the game that it should check to see which of the nation's nine holds the player is in, so that the hold's name may be displayed.", dis_d)),
      _info('KWUA', QObject::tr("Keyword - UpdateDuringArchery", dis_n)),
      _info('LHEQ', QObject::tr("LeftHand Equip", dis_n)),
      _info('LKHO', QObject::tr("Keyword - Hold Location", dis_n)),
      _info('LKPK', QObject::tr("Lockpick", dis_n), QObject::tr("The MiscObject used as a breakable lockpick.", dis_d)),
      _info('LMHP', QObject::tr("Local Map Hide Plane", dis_n)),
      _info('LRRD', QObject::tr("LocRefType - Resource Destructible", dis_n)),
      _info('LRSO', QObject::tr("LocRefType - Civil War Soldier", dis_n)),
      _info('LRTB', QObject::tr("LocRefType Boss", dis_n), QObject::tr("A LocRefType used for boss enemies. It is primarily used as part of the location ref type system, but it has other scattered uses; for example, the VATS killcam system will skip several checks when deciding whether to play killcams on bosses.", dis_d)),
      _info('LSIS', QObject::tr("Imagespace: Load screen", dis_n)),
      _info('LUMS', QObject::tr("Level Up Music", dis_n)),
      _info('MDSC', QObject::tr("Music Sound Category", dis_n)),
      _info('MFSN', QObject::tr("Magic Fail Sound", dis_n)),
      _info('MGGF', QObject::tr("Mages' Guild Faction", dis_n)),
      _info('MMCL', QObject::tr("Main Menu Cell", dis_n)),
      _info('MMSD', QObject::tr("Map Menu Looping Sound", dis_n)),
      _info('MNT2', QObject::tr("Keyword - Mount", dis_n)),
      _info('MTSC', QObject::tr("Master Sound Category", dis_n)),
      _info('MVBL', QObject::tr("Keyword - Movable", dis_n)),
      _info('NASD', QObject::tr("No-Activation Sound", dis_n)),
      _info('NDSC', QObject::tr("Non-Dialogue Voice Category", dis_n)),
      _info('NMRD', QObject::tr("Road Marker", dis_n)),
      _info('NPCK', QObject::tr("Keyword - NPC", dis_n)),
      _info('NRNT', QObject::tr("Keyword - Nirnroot", dis_n)),
      _info('P3OM', QObject::tr("Player's Output Model (3rd Person)", dis_n)),
      _info('PCMD', QObject::tr("Player Can Mount Dragon Here List", dis_n)),
      _info('PDLC', QObject::tr("Pause During Loading Menu Category", dis_n)),
      _info('PDMC', QObject::tr("Pause During Menu Category (Fade)", dis_n)),
      _info('PDSA', QObject::tr("Putdown Sound Armor", dis_n)),
      _info('PDSB', QObject::tr("Putdown Sound Book", dis_n)),
      _info('PDSG', QObject::tr("Putdown Sound Generic", dis_n)),
      _info('PDSI', QObject::tr("Putdown Sound Ingredient", dis_n)),
      _info('PDSW', QObject::tr("Putdown Sound Weapon", dis_n)),
      _info('PFAC', QObject::tr("Player Faction", dis_n), QObject::tr("A faction used for the player and for things that should belong to the player, such as projectiles that they have fired.", dis_d)),
      _info('PIMC', QObject::tr("Pause During Menu Category (Immediate)", dis_n)),
      _info('PIVV', QObject::tr("Player Is Vampire Variable", dis_n)),
      _info('PIWV', QObject::tr("Player Is Werewolf Variable", dis_n)),
      _info('PLOC', QObject::tr("PersistAll Location", dis_n)),
      _info('PLST', QObject::tr("Default Pack List", dis_n)),
      _info('POEQ', QObject::tr("Potion Equip", dis_n)),
      _info('POPM', QObject::tr("Player's Output Model (1st Person)", dis_n)),
      _info('PTEM', QObject::tr("Package template", dis_n)),
      _info('PTFR', QObject::tr("PotentialFollower Faction", dis_n)),
      _info('PTNP', QObject::tr("Pathing Test NPC", dis_n)),
      _info('PUSA', QObject::tr("Pickup Sound Armor", dis_n)),
      _info('PUSB', QObject::tr("Pickup Sound Book", dis_n)),
      _info('PUSG', QObject::tr("Pickup Sound Generic", dis_n)),
      _info('PUSI', QObject::tr("Pickup Sound Ingredient", dis_n)),
      _info('PUSW', QObject::tr("Pickup Sound Weapon", dis_n)),
      _info('PVFA', QObject::tr("Player Voice (Female)", dis_n)),
      _info('PVFC', QObject::tr("Player Voice (Female Child)", dis_n)),
      _info('PVMA', QObject::tr("Player Voice (Male)", dis_n)),
      _info('PVMC', QObject::tr("Player Voice (Male Child)", dis_n)),
      _info('PWFD', QObject::tr("Wait-For-Dialogue Package", dis_n)),
      _info('RHEQ', QObject::tr("RightHand Equip", dis_n)),
      _info('RIVR', QObject::tr("Vampire Race", dis_n)),
      _info('RIVS', QObject::tr("Vampire Spells", dis_n)),
      _info('RIWR', QObject::tr("Werewolf Race", dis_n)),
      _info('RUSG', QObject::tr("Keyword - Reusable SoulGem", dis_n), QObject::tr("Soul gems with this keyword are reusable instead of single-use.", dis_d)),
      _info('RVBT', QObject::tr("Reverb Type", dis_n)),
      _info('SALT', QObject::tr("Sitting Angle Limit", dis_n)),
      _info('SAT1', QObject::tr("Keyword: Scale Actor To 1.0", dis_n), QObject::tr("Actors will have their scale temporarily forced to 1.0 while using any furniture that has this keyword.", dis_d)),
      _info('SCMS', QObject::tr("Success Music", dis_n)),
      _info('SCSD', QObject::tr("Soul Captured Sound", dis_n), QObject::tr("A sound played when the player successfully captures the soul of a killed actor using Soul Trap.", dis_d)),
      _info('SFDC', QObject::tr("SFX To Fade In Dialogue Category", dis_n)),
      _info('SFSN', QObject::tr("Shout Fail Sound", dis_n)),
      _info('SKLK', QObject::tr("SkeletonKey", dis_n), QObject::tr("A MiscObject that serves as an unbreakable lockpick.", dis_d)),
      _info('SLDM', QObject::tr("Snow LOD Material", dis_n)),
      _info('SLHD', QObject::tr("Snow LOD Material (HD)", dis_n)),
      _info('SMLT', QObject::tr("Keyword: Smelter", dis_n), QObject::tr("Workbenches with this keyword are treated as smelters. The keyword is used to decide which tutorial message to display to the player.", dis_d)),
      _info('SMSC', QObject::tr("Stats Mute Category", dis_n)),
      _info('SPFK', QObject::tr("Keyword - Special Furniture", dis_n)),
      _info('SSSC', QObject::tr("Stats Music", dis_n)),
      _info('TANN', QObject::tr("Keyword: Tanning Rack", dis_n), QObject::tr("Workbenches with this keyword are treated as tanning racks. The keyword is used to decide which tutorial message to display to the player.", dis_d)),
      _info('TKAM', QObject::tr("Keyword - Type Ammo", dis_n)),
      _info('TKAR', QObject::tr("Keyword - Type Armor", dis_n)),
      _info('TKBK', QObject::tr("Keyword - Type Book", dis_n)),
      _info('TKGS', QObject::tr("Telekinesis Grab Sound", dis_n)),
      _info('TKIG', QObject::tr("Keyword - Type Ingredient", dis_n)),
      _info('TKKY', QObject::tr("Keyword - Type Key", dis_n)),
      _info('TKMS', QObject::tr("Keyword - Type Misc", dis_n)),
      _info('TKPT', QObject::tr("Keyword - Type Potion", dis_n)),
      _info('TKSG', QObject::tr("Keyword - Type SoulGem", dis_n)),
      _info('TKTS', QObject::tr("Telekinesis Throw Sound", dis_n)),
      _info('TKWP', QObject::tr("Keyword - Type Weapon", dis_n)),
      _info('TSSC', QObject::tr("Time Sensitive Sound Category", dis_n)),
      _info('TVGF', QObject::tr("Thieves' Guild Faction", dis_n)),
      _info('UNDK', QObject::tr("Keyword - Undead", dis_n)),
      _info('URVT', QObject::tr("Underwater Reverb Type", dis_n)),
      _info('UWLS', QObject::tr("Underwater Loop Sound", dis_n)),
      _info('VAMP', QObject::tr("Keyword: Vampire", dis_n)),
      _info('VFNC', QObject::tr("Vampire Feed No Crime Faction", dis_n)),
      _info('VLOC', QObject::tr("Virtual Location", dis_n)),
      _info('VOEQ', QObject::tr("Voice Equip", dis_n)),
      _info('WASN', QObject::tr("Ward Absorb Sound", dis_n)),
      _info('WBSN', QObject::tr("Ward Break Sound", dis_n)),
      _info('WDSN', QObject::tr("Ward Deflect Sound", dis_n)),
      _info('WEML', QObject::tr("Weapon Material List", dis_n)),
      _info('WMDA', QObject::tr("Keyword - Weapon Material Daedric", dis_n)),
      _info('WMDH', QObject::tr("Keyword - Weapon Material DraugrHoned", dis_n)),
      _info('WMDR', QObject::tr("Keyword - Weapon Material Draugr", dis_n)),
      _info('WMDW', QObject::tr("Keyword - Weapon Material Dwarven", dis_n)),
      _info('WMEB', QObject::tr("Keyword - Weapon Material Ebony", dis_n)),
      _info('WMEL', QObject::tr("Keyword - Weapon Material Elven", dis_n)),
      _info('WMFA', QObject::tr("Keyword - Weapon Material Falmer", dis_n)),
      _info('WMFH', QObject::tr("Keyword - Weapon Material FalmerHoned", dis_n)),
      _info('WMGL', QObject::tr("Keyword - Weapon Material Glass", dis_n)),
      _info('WMIM', QObject::tr("Keyword - Weapon Material Imperial", dis_n)),
      _info('WMIR', QObject::tr("Keyword - Weapon Material Iron", dis_n)),
      _info('WMOR', QObject::tr("Keyword - Weapon Material Orcish", dis_n)),
      _info('WMST', QObject::tr("Keyword - Weapon Material Steel", dis_n)),
      _info('WMWE', QObject::tr("World Map Weather", dis_n)),
      _info('WMWO', QObject::tr("Keyword - Weapon Material Wood", dis_n)),
      _info('WPNC', QObject::tr("Keyword - Weapon Material Nordic", dis_n)),
      _info('WPSM', QObject::tr("Keyword - Weapon Material Stalhrim", dis_n)),
      _info('WTBA', QObject::tr("Keyword - WeaponTypeBoundArrow", dis_n), QObject::tr("A keyword meant to be applied to bound arrow base forms. Its uses include preventing the player from recovering bound arrows after they have been fired.", dis_d)),
      _info('WWSP', QObject::tr("Werewolf Spell", dis_n)),
   };
}
extern QString get_default_object_name(uint32_t signature) {
   if (!signature)
      return QString();
   for (auto& entry : _default_objects) {
      if (entry.signature == signature)
         return entry.name;
   }
   return QString();
}
extern QString get_default_object_description(uint32_t signature) {
   if (!signature)
      return QString();
   for (auto& entry : _default_objects) {
      if (entry.signature == signature)
         return entry.description;
   }
   return QString();
}

extern bool for_each_default_object(std::function<bool(uint32_t s, const QString& n, const QString& d)> functor) {
   for (auto& entry : _default_objects) {
      if (functor(entry.signature, entry.name, entry.description))
         return true;
   }
   return false;
}