#include "get_game_setting_description.h"
#include <array>
#include <QObject>

//
// These should be localized, so I don't want to embed them into the backend.
//

namespace {
   const char* disambig = "GMST description";

   struct _association {
      const char* name;
      QString     description;
      //
      _association() {}
      _association(const char* c, const QString& s) : name(c), description(s) {}
   };
   std::array _associations = {
      _association("fDetectionUpdateTimeMaxComplex", QObject::tr("This is used in place of fDetectionUpdateTimeMax if any attached cells contain ComplexSceneMarkers.", disambig)),
      _association("fDetectionUpdateTimeMinComplex", QObject::tr("This is used in place of fDetectionUpdateTimeMin if any attached cells contain ComplexSceneMarkers.", disambig)),
      //
      _association("fActiveEffectConditionUpdateInterval", QObject::tr("The time interval, in seconds, on which active effects recheck their conditions and their elapsed time. Each active effect has its own independent timer beginning when the effect is first applied.", disambig)),
      _association("fBlinkDelayMax",                 QObject::tr("The upper bound on the random number of seconds that pass between each time a character blinks their eyes. The lower bound is fBlinkDelayMin.", disambig)), // TODO: Definition from CS wiki; double-check that Skyrim still uses this.
      _association("fBlinkDelayMin",                 QObject::tr("The lower bound on the random number of seconds that pass between each time a character blinks their eyes. The upper bound is fBlinkDelayMax.", disambig)), // TODO: Definition from CS wiki; double-check that Skyrim still uses this.
      _association("fBlinkDownTime",                 QObject::tr("The total number of seconds that a blinking character spends closing their eyes and keeping them closed.", disambig)), // TODO: Definition from CS wiki; double-check that Skyrim still uses this.
      _association("fBlinkUpTime",                   QObject::tr("The number of seconds it takes for a blinking character's eyes to move from fully closed to fully open.", disambig)),  // TODO: Definition from CS wiki; double-check that Skyrim still uses this.
      _association("fEssentialDeathTime",            QObject::tr("The number of seconds that an essential actor stays in bleedout once their health is drained.", disambig)),
      _association("fGameplayVoiceFilePadding",      QObject::tr("The number of seconds of silence that Skyrim inserts between consecutive voice lines. This is the setting that makes every bard song sound awkward and disjointed.", disambig)),
      _association("fMagicAbsorbVisualTimer",        QObject::tr("The duration in seconds of a visual effect played on actors when they absorb a spell. The visual effect itself is defined as a Default Object.", disambig)),
      _association("fMineAgeMax",                    QObject::tr("If this is set to zero, then armed landmines persist in the game world indefinitely; otherwise, this setting is the number of seconds it takes for a landmine to disappear after being armed. Although landmines are exclusive to Fallout 3, this setting is referenced in Skyrim's code, though under unclear circumstances.", disambig)),
      _association("fNPCGeneticVariation",           QObject::tr("Unused.", disambig)),
      _association("fPotionMortPestleMult",          QObject::tr("Unused. In Oblivion, this setting determined the influence of a mortar and pestle when performing alchemy.", disambig)),
      //
      _association("iActivatePickLength",     QObject::tr("Effectively unused. In past games, this determined the distance (in world units) from which the player could activate objects, but it no longer serves that function in Skyrim. It does serve as the player's default melee range if they don't have a weapon drawn or their fists raised... which are not conditions under which the player logically should be able to melee. If the player has a weapon drawn or their fists raised, then their melee range is determined by fObjectHitTwoHandReach (for two-handed weapons including bows, staves, and crossbows), fObjectHitWeaponReach (for one-handed weapons), or fObjectHitH2HReach (for unarmed).", disambig)),
      _association("iArrowMaxCount",          QObject::tr("Unused.", disambig)),
      _association("iAvoidHurtingNonTargetsResponsibility", QObject::tr("Unused.", disambig)),
      _association("iClassAcrobat",           QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassAgent",             QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassArcher",            QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassAssassin",          QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassBarbarian",         QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassBard",              QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassBattlemage",        QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassCharactergenClass", QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassCrusader",          QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassHealer",            QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassKnight",            QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassMage",              QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassMonk",              QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassNightblade",        QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassPilgrim",           QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassPriest",            QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassRogue",             QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassScout",             QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassSorcerer",          QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassSpellsword",        QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassThief",             QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassWarrior",           QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iClassWitchhunter",       QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iHairColor00",            QObject::tr("Unused. In past games, this was one of the predefined hair colors available for the player to select in character creation. The value was a hexadecimal color code (RGB; upper byte unused) represented as an integer.", disambig)),
      _association("iHairColor01",            QObject::tr("Unused. In past games, this was one of the predefined hair colors available for the player to select in character creation. The value was a hexadecimal color code (RGB; upper byte unused) represented as an integer.", disambig)),
      _association("iHairColor02",            QObject::tr("Unused. In past games, this was one of the predefined hair colors available for the player to select in character creation. The value was a hexadecimal color code (RGB; upper byte unused) represented as an integer.", disambig)),
      _association("iHairColor03",            QObject::tr("Unused. In past games, this was one of the predefined hair colors available for the player to select in character creation. The value was a hexadecimal color code (RGB; upper byte unused) represented as an integer.", disambig)),
      _association("iHairColor04",            QObject::tr("Unused. In past games, this was one of the predefined hair colors available for the player to select in character creation. The value was a hexadecimal color code (RGB; upper byte unused) represented as an integer.", disambig)),
      _association("iHairColor05",            QObject::tr("Unused. In past games, this was one of the predefined hair colors available for the player to select in character creation. The value was a hexadecimal color code (RGB; upper byte unused) represented as an integer.", disambig)),
      _association("iHairColor06",            QObject::tr("Unused. In past games, this was one of the predefined hair colors available for the player to select in character creation. The value was a hexadecimal color code (RGB; upper byte unused) represented as an integer.", disambig)),
      _association("iHairColor07",            QObject::tr("Unused. In past games, this was one of the predefined hair colors available for the player to select in character creation. The value was a hexadecimal color code (RGB; upper byte unused) represented as an integer.", disambig)),
      _association("iHairColor08",            QObject::tr("Unused. In past games, this was one of the predefined hair colors available for the player to select in character creation. The value was a hexadecimal color code (RGB; upper byte unused) represented as an integer.", disambig)),
      _association("iHairColor09",            QObject::tr("Unused. In past games, this was one of the predefined hair colors available for the player to select in character creation. The value was a hexadecimal color code (RGB; upper byte unused) represented as an integer.", disambig)),
      _association("iHairColor10",            QObject::tr("Unused. In past games, this was one of the predefined hair colors available for the player to select in character creation. The value was a hexadecimal color code (RGB; upper byte unused) represented as an integer.", disambig)),
      _association("iHairColor11",            QObject::tr("Unused. In past games, this was one of the predefined hair colors available for the player to select in character creation. The value was a hexadecimal color code (RGB; upper byte unused) represented as an integer.", disambig)),
      _association("iHairColor12",            QObject::tr("Unused. In past games, this was one of the predefined hair colors available for the player to select in character creation. The value was a hexadecimal color code (RGB; upper byte unused) represented as an integer.", disambig)),
      _association("iHairColor13",            QObject::tr("Unused. In past games, this was one of the predefined hair colors available for the player to select in character creation. The value was a hexadecimal color code (RGB; upper byte unused) represented as an integer.", disambig)),
      _association("iHairColor14",            QObject::tr("Unused. In past games, this was one of the predefined hair colors available for the player to select in character creation. The value was a hexadecimal color code (RGB; upper byte unused) represented as an integer.", disambig)),
      _association("iHairColor15",            QObject::tr("Unused. In past games, this was one of the predefined hair colors available for the player to select in character creation. The value was a hexadecimal color code (RGB; upper byte unused) represented as an integer.", disambig)),
      _association("iHoursToRespawnCell",        QObject::tr("The number of in-game hours that must pass before a cell that hasn't been cleared will reset.", disambig)),
      _association("iHoursToRespawnCellCleared", QObject::tr("The number of in-game hours that must pass before a cell that has been cleared will reset.", disambig)),
      _association("iInventoryAskQuantityAt", QObject::tr("When dropping items from your inventory, you will be prompted to select a quantity if you have more than this many of an item.", disambig)),
      _association("iMaxArrowsInQuiver",      QObject::tr("When the player has arrows equipped, a quiver is rendered on their back. The number of arrows visible in the quiver actually varies depending on how many arrows of that type the player has in their inventory. The game achieves this effect by toggling the visibility of 3D nodes in the quiver's 3D model, with the node names following the convention \"Arrow#\" e.g. Arrow1, Arrow2, Arrow15, and so on. This game setting determines the maximum number of arrow nodes that the game will check for and manage.", disambig)),
      _association("iMaxAttachedArrows",      QObject::tr("The maximum number of arrows or similar projectiles that can be stuck in a body. This is purely cosmetic.", disambig)),
      _association("iMaxCharacterLevel",      QObject::tr("Unused. In Oblivion and Fallout, this setting determined the maximum level that the player could reach.", disambig)),
      _association("iMaxPlayerRunes",         QObject::tr("The maximum number of runes that the player can have active at a time.", disambig)),
      _association("iMaxSummonedCreatures",   QObject::tr("The maximum number of summoned creatures that the player can have at a time.", disambig)),
      _association("iMineDisarmExperience",   QObject::tr("Unused. In Fallout, this was the number of experience points that the player gained for disarming a live landmine.", disambig)),
      _association("iPlayerCustomClass",      QObject::tr("Unused. In Oblivion, this was the global form ID of one of the classes available for the player to select during character creation. The setting is no longer checked in Skyrim, and no longer needs to refer to a valid form ID.", disambig)),
      _association("iXPLevelSpeechChallengeVeryEasy", QObject::tr("Unused.", disambig)),
      _association("iXPLevelSpeechChallengeEasy",     QObject::tr("Unused.", disambig)),
      _association("iXPLevelSpeechChallengeAverage",  QObject::tr("Unused.", disambig)),
      _association("iXPLevelSpeechChallengeHard",     QObject::tr("Unused.", disambig)),
      _association("iXPLevelSpeechChallengeVeryHard", QObject::tr("Unused.", disambig)),
      _association("iVATSConcentratedFireBonus",      QObject::tr("Unused. Used in Fallout to compute the accuracy percentage bonus conferred by the Concentrated Fire perk when launching multiple consecutive strikes on the same target in VATS.", disambig)),
      //
      _association("sActivationChoiceMessage",   QObject::tr("The text of a message box menu displayed when the player activates an object, if the player's perks result in them having multiple activation choices for the object.", disambig)),
      _association("sAlchemy",                   QObject::tr("The title of the alchemy menu, shown at the top of the menu layout with the description (sAlchemyMenuDescription). The title and description are inserted into the format string \"%s: %s\".", disambig)),
      _association("sAlchemyMenuDescription",    QObject::tr("Descriptive text for the alchemy menu, shown at the top of the menu layout with the title (sAlchemy). The title and description are inserted into the format string \"%s: %s\".", disambig)),
      _association("sAlreadyKnown",              QObject::tr("The error message shown when the player attempts to read a spell book after they have already learned its spell. The spell name will be appended to this string, separated by a single space.", disambig)),
      _association("sAmber",                     QObject::tr("Unused. A color option for Fallout's Pip-Boy and associated UI.", disambig)),
      _association("sAnimationCanNotUnequip",    QObject::tr("Unused. An error message telling the player that they cannot equip or unequip weapons during an attack animation.", disambig)),
      _association("sAreaText",                  QObject::tr("Unused. The label for a spell's area, as shown in Oblivion's spellmaking menu.", disambig)),
      _association("sAttributeDrained",          QObject::tr("Unused.", disambig)),
      _association("sBroken",                    QObject::tr("Unused. A lock level string shown in Fallout 3's lockpicking menu, when interacting with a lock that was broken after the player tried and failed to force it.", disambig)),
      // setting name is wrong // _association("sButtonLocked",              QObject::tr("Unused. HUD text displayed when aiming at a door or container with a broken lock. Locks could be broken in Fallout, if an attempt at forcing them failed.", disambig)),
      _association("sCannotCastShout",           QObject::tr("Notification shown when the player attempts to cast a shout while their shouts are on cooldown.", disambig)),
      _association("sCanNotReadBook",            QObject::tr("Unused. Error message displayed in past games when attempting to read a book while in combat.", disambig)),
      _association("sCantEquipBrokenItem",       QObject::tr("Unused. Error message displayed in past games when attempting to equip a broken weapon or piece of armor.", disambig)),
      _association("sCantEquipPowerArmor",       QObject::tr("Unused. Error message displayed when trying to equip Power Armor in Fallout without the appropriate perk.", disambig)),
      _association("sCharGenControlsDisabled",   QObject::tr("Notification shown when the player attempts to perform gameplay actions while gameplay controls are disabled and CharGen has been flagged as active.", disambig)),
      _association("sChemsAddicted",             QObject::tr("Unused. Notification shown in Fallout when a player becomes addicted to a chem.", disambig)),
      _association("sChemsWithdrawal",           QObject::tr("Unused. Notification shown in Fallout when a chem-addicted player is in withdrawal.", disambig)),
      _association("sChemsWornOff",              QObject::tr("Unused. Notification shown in Fallout when a chem that the player has taken wears off.", disambig)),
      _association("sConfirmAttribute",          QObject::tr("The text of a confirmation prompt shown when the player chooses a stat (from among Health, Magicka, and Stamina) to increase after leveling up.", disambig)),
      _association("sConfirmContinue",           QObject::tr("The text of a confirmation prompt shown when the player chooses \"Continue\" in the main menu, to continue playing their last save.", disambig)),
      _association("sConfirmDisenchant",         QObject::tr("The text of a confirmation prompt shown when the player attempts to disenchant an item using an enchanting station.", disambig)),
      _association("sConfirmSpendSoul",          QObject::tr("The text of a confirmation prompt shown when the player chooses to unlock a word of power using a dragon soul.", disambig)),
      _association("sContainerPlaceChance",      QObject::tr("Unused. Text shown in Fallout's pickpocketing menu when attempting to covertly place one's own items in another NPC's inventory.", disambig)),
      _association("sContractedDisease",         QObject::tr("Part of the text of a notification shown when the player is infected with a disease. It is the first parameter passed to the hardcoded format string \"%s %s.\" The second parameter is the name of the disease.", disambig)),
      _association("sCreatedPoisonNamePrefix",   QObject::tr("Part of the default name for player-created poisons. The auto-generated effect name is appended to this text.", disambig)),
      _association("sCreatedPotionNamePrefix",   QObject::tr("Part of the default name for player-created potions. The auto-generated effect name is appended to this text.", disambig)),
      _association("sCriticalStrike",            QObject::tr("Notification shown to the player when they land a critical strike on an actor. The attacked actor's name will be appended to the text, separated with a single space.", disambig)),
      _association("sCursorFilename",            QObject::tr("Unused. The path to the mouse cursor texture; a leftover from Oblivion's UI engine.", disambig)),
      _association("sDefaultCellName",           QObject::tr("The default name displayed in the UI for any exterior cell that lacks a name or editor ID.", disambig)),
      _association("sDefaultCubeMap",            QObject::tr("The texture file path for the default cubemap used for water in any cell that doesn't specify a water environment map. The \"data\\textures\\\" prefix should be omitted from the path.", disambig)),
      _association("SDropQuestItemWarning",      QObject::tr("Error notification shown when the player attempts to drop a quest item or place it into a container not associated with the same quest.", disambig)),
      _association("sEffectAlreadyAdded",        QObject::tr("Unused. A leftover from Oblivion's spellmaking menu.", disambig)),
      _association("sEmpty",                     QObject::tr("An annotation shown next to the activation prompt, when aiming at a container or corpse with an empty inventory.", disambig)),
      _association("sEnchantItem",               QObject::tr("The text of a confirmation prompt shown when the player chooses to enchant an item.", disambig)),
      _association("sEnchantmentKnown",          QObject::tr("Error message shown when the player attempts to disenchant an item whose enchantments are already known.", disambig)),
      _association("sFailSpendSoul",             QObject::tr("Error message shown when the player attempts to unlock a word of power when they don't have any dragon souls.", disambig)),
      _association("sFastTravelNoTravelHealthDamage", QObject::tr("Error notification shown when the player attempts to fast-travel while taking health damage.", disambig)),
      _association("sGenericCraftKeywordName01", QObject::tr("The name of the first of ten \"generic\" crafting menu categories that were reserved on launch for use by future content; the name is stylized in all-caps. The Hearthfire DLC eventually renamed this to the \"House\" category.", disambig)),
      _association("sGenericCraftKeywordName02", QObject::tr("The name of the second of ten \"generic\" crafting menu categories that were reserved on launch for use by future content; the name is stylized in all-caps. The Hearthfire DLC eventually renamed this to the \"Containers\" category.", disambig)),
      _association("sGenericCraftKeywordName03", QObject::tr("The name of the third of ten \"generic\" crafting menu categories that were reserved on launch for use by future content; the name is stylized in all-caps. The Hearthfire DLC eventually renamed this to the \"Furniture\" category.", disambig)),
      _association("sGenericCraftKeywordName04", QObject::tr("The name of the fourth of ten \"generic\" crafting menu categories that were reserved on launch for use by future content; the name is stylized in all-caps. The Hearthfire DLC eventually renamed this to the \"Weapon Racks\" category.", disambig)),
      _association("sGenericCraftKeywordName05", QObject::tr("The name of the fifth of ten \"generic\" crafting menu categories that were reserved on launch for use by future content; the name is stylized in all-caps. The Hearthfire DLC eventually renamed this to the \"Shelves\" category.", disambig)),
      _association("sGenericCraftKeywordName06", QObject::tr("The name of the sixth of ten \"generic\" crafting menu categories that were reserved on launch for use by future content; the name is stylized in all-caps. The Hearthfire DLC eventually renamed this to the \"Exterior\" category.", disambig)),
      _association("sGenericCraftKeywordName07", QObject::tr("The name of the seventh of ten \"generic\" crafting menu categories that were reserved on launch for use by future content; the name is stylized in all-caps. The Hearthfire DLC eventually renamed this to the \"Building Materials\" category.", disambig)),
      _association("sGenericCraftKeywordName08", QObject::tr("The name of the eighth of ten \"generic\" crafting menu categories that were reserved on launch for use by future content; the name is stylized in all-caps.", disambig)),
      _association("sGenericCraftKeywordName09", QObject::tr("The name of the ninth of ten \"generic\" crafting menu categories that were reserved on launch for use by future content; the name is stylized in all-caps.", disambig)),
      _association("sGenericCraftKeywordName10", QObject::tr("The name of the tenth of ten \"generic\" crafting menu categories that were reserved on launch for use by future content; the name is stylized in all-caps. The Dawnguard DLC eventually renamed this to the \"Aetherium\" category.", disambig)),
      _association("sGotAwayWithStealing",       QObject::tr("Unused.", disambig)),
      _association("sHairColor00",               QObject::tr("Unused. In past games, this was the name of one of the predefined hair colors available for the player to select in character creation.", disambig)),
      _association("sHairColor01",               QObject::tr("Unused. In past games, this was the name of one of the predefined hair colors available for the player to select in character creation.", disambig)),
      _association("sHairColor02",               QObject::tr("Unused. In past games, this was the name of one of the predefined hair colors available for the player to select in character creation.", disambig)),
      _association("sHairColor03",               QObject::tr("Unused. In past games, this was the name of one of the predefined hair colors available for the player to select in character creation.", disambig)),
      _association("sHairColor04",               QObject::tr("Unused. In past games, this was the name of one of the predefined hair colors available for the player to select in character creation.", disambig)),
      _association("sHairColor05",               QObject::tr("Unused. In past games, this was the name of one of the predefined hair colors available for the player to select in character creation.", disambig)),
      _association("sHairColor06",               QObject::tr("Unused. In past games, this was the name of one of the predefined hair colors available for the player to select in character creation.", disambig)),
      _association("sHairColor07",               QObject::tr("Unused. In past games, this was the name of one of the predefined hair colors available for the player to select in character creation.", disambig)),
      _association("sHairColor08",               QObject::tr("Unused. In past games, this was the name of one of the predefined hair colors available for the player to select in character creation.", disambig)),
      _association("sHairColor09",               QObject::tr("Unused. In past games, this was the name of one of the predefined hair colors available for the player to select in character creation.", disambig)),
      _association("sHairColor10",               QObject::tr("Unused. In past games, this was the name of one of the predefined hair colors available for the player to select in character creation.", disambig)),
      _association("sHairColor11",               QObject::tr("Unused. In past games, this was the name of one of the predefined hair colors available for the player to select in character creation.", disambig)),
      _association("sHairColor12",               QObject::tr("Unused. In past games, this was the name of one of the predefined hair colors available for the player to select in character creation.", disambig)),
      _association("sHairColor13",               QObject::tr("Unused. In past games, this was the name of one of the predefined hair colors available for the player to select in character creation.", disambig)),
      _association("sHairColor14",               QObject::tr("Unused. In past games, this was the name of one of the predefined hair colors available for the player to select in character creation.", disambig)),
      _association("sHairColor15",               QObject::tr("Unused. In past games, this was the name of one of the predefined hair colors available for the player to select in character creation.", disambig)),
      _association("sHandToHandIcon",            QObject::tr("Unused. A leftover from Oblivion's UI engine.", disambig)),
      _association("sHeavyArmorNoJump",          QObject::tr("Unused. It is notification text telling the player that they are unable to jump because they are wearing heavy armor.", disambig)),
      _association("sHeavyArmorSink",            QObject::tr("Unused. It is notification text telling the player that they are unable to swim because they are wearing heavy armor.", disambig)),
      _association("sImpossibleLock",            QObject::tr("Error notification shown when attempting to pick a lock that can't be picked.", disambig)),
      _association("sInaccessible",              QObject::tr("Unused. Text from Fallout 3's HUD, shown in place of a lock level when aiming at an impossible-to-unlock door with no associated key.", disambig)),
      _association("sLackRequiredPerksToImprove",       QObject::tr("The error message shown to the player when they attempt to improve an item at a smithing station, but lack the perks needed.", disambig)),
      _association("sLackRequiredPerkToImproveMagical", QObject::tr("The error message shown to the player when they attempt to improve an enchanted item at a smithing station, but lack the perks needed.", disambig)),
      _association("sLegendaryResetConfirm",       QObject::tr("The text of the first of two confirmation prompts shown when the user attempts to reset a skill, making it Legendary.", disambig)),
      _association("sLegendaryResetSecondConfirm", QObject::tr("The text of the last of two confirmation prompts shown when the user attempts to reset a skill, making it Legendary.", disambig)),
      _association("sMagicDeliveryTouch",        QObject::tr("Unused. A spell casting type displayed in Oblivion's spellmaking menu.", disambig)),
      _association("sMagicGuideNoMarker",        QObject::tr("Notification shown when the player attempts to use a Guide-archetype spell without an active quest set.", disambig)),
      _association("sMagicGuideNoPath",          QObject::tr("Notification shown when the player attempts to use a Guide-archetype spell when the target of their active quest is unreachable.", disambig)),
      _association("sMiscPlayerDeadMessage",     QObject::tr("A message displayed when the player is killed. The exact circumstances under which this is displayed are not clear.", disambig)),
      _association("sMultipleDragonSoulCount",   QObject::tr("Text used to display the number of dragon souls that the player has, if it's more than one; the format string for the singular is sSingleDragonSoulCount. The format string parameter is the number (integer) of souls.", disambig)),
      _association("sNoChildUse",                QObject::tr("Unused. Error notification shown when the player is a child and attempts to interact with non-child furniture.", disambig)),
      _association("sNoEatQuestItem",            QObject::tr("Error notification shown when the player attempts to eat a quest item that is classified as an ingredient or potion (the latter would include most food items).", disambig)),
      _association("sNoFastTravelAlarm",         QObject::tr("Error notification shown when the player attempts to fast-travel while being pursued by guards.", disambig)),
      _association("sNoFastTravelCell",          QObject::tr("Error notification shown when the player attempts to fast-travel from a location that doesn't allow fast-traveling.", disambig)),
      _association("sNoFastTravelCombat",        QObject::tr("Unused. Text of an error message shown when the player attempts to fast-travel while in combat.", disambig)),
      _association("sNoFastTravelDefault",       QObject::tr("Error notification shown when the player attempts to fast-travel, but is unable to for an unexplained reason.", disambig)),
      _association("sNoFastTravelInAir",         QObject::tr("Error notification shown when the player attempts to fast-travel while in midair.", disambig)),
      _association("sNoFastTravelOverencumbered", QObject::tr("Unused. Text of an error message shown when the player attempts to fast-travel while overencumbered.", disambig)),
      _association("sNoFastTravelScriptBlock",   QObject::tr("Error notification shown when the player attempts to fast-travel while Papyrus scripts have disabled fast-traveling.", disambig)),
      _association("sNoKeyDropWarning",          QObject::tr("Error notification shown when the player attempts to drop keys.", disambig)),
      _association("sNoPickPocketAgain",         QObject::tr("Error notification shown when the player tries to pickpocket an NPC that has previously caught them pickpocketing. The NPC's name is prepended to the text.", disambig)),
      _association("sNoSleepDefault",            QObject::tr("Error notification shown when the player attempts to sleep, but is unable to for an unexplained reason.", disambig)),
      _association("sNoSleepHostileActorsNear",  QObject::tr("Error notification shown when the player attempts to sleep while hostile actors are nearby.", disambig)),
      _association("sNoSleepInAir",              QObject::tr("Error notification shown when the player attempts to sleep while in midair.", disambig)),
      _association("sNoSleepInCell",             QObject::tr("Error notification shown when the player attempts to sleep in a cell that doesn't allow sleeping or waiting.", disambig)),
      _association("sNoSleepInOwnedBed",         QObject::tr("Error notification shown when the player attempts to use a bed that is owned by another actor.", disambig)),
      _association("sNoSleepTakingHealthDamage", QObject::tr("Error notification shown when the player attempts to sleep while taking health damage.", disambig)),
      _association("sNoSleepTrespass",           QObject::tr("Error notification shown when the player attempts to sleep while trespassing.", disambig)),
      _association("sNoSleepWarnToLeave",        QObject::tr("Error notification shown when the player attempts to sleep while trespassing and being ordered to leave.", disambig)),
      _association("sNoSleepWhileAlarm",         QObject::tr("Error notification shown when the player attempts to sleep while being pursued by guards.", disambig)),
      _association("sNoWaitDefault",             QObject::tr("Error notification shown when the player attempts to wait, but is unable to for an unexplained reason.", disambig)),
      _association("sNoWaitHostileActorsNear",   QObject::tr("Error notification shown when the player attempts to wait while hostile actors are nearby.", disambig)),
      _association("sNoWaitInAir",               QObject::tr("Error notification shown when the player attempts to wait while in midair.", disambig)),
      _association("sNoWaitInCell",              QObject::tr("Error notification shown when the player attempts to wait in a cell that doesn't allow sleeping or waiting.", disambig)),
      _association("sNoWaitTakingHealthDamage",  QObject::tr("Error notification shown when the player attempts to wait while taking health damage.", disambig)),
      _association("sNoWaitTrespass",            QObject::tr("Error notification shown when the player attempts to wait while trespassing.", disambig)),
      _association("sNoWaitWarnToLeave",         QObject::tr("Error notification shown when the player attempts to wait while trespassing and being ordered to leave.", disambig)),
      _association("sNoWaitWhileAlarm",          QObject::tr("Error notification shown when the player attempts to wait while being pursued by guards.", disambig)),
      _association("sObjectInUse",               QObject::tr("Error notification shown when the player attempts to use a furniture object that another actor is already using.", disambig)),
      _association("sOpenWithKey",               QObject::tr("Notification shown when the player unlocks a door using a key. The format string parameter is the name of the key.", disambig)),
      _association("sOutOfLockpicks",            QObject::tr("Error notification displayed when the player tries to pick a lock without carrying any lockpicks, or when they are booted from the lockpicking menu after breaking their last lockpick.", disambig)),
      _association("sOverEncumbered",            QObject::tr("Notification shown when the player is overencumbered. This notification is displayed every thirty seconds of gameplay, or forcibly displayed (resetting the timer) when the player's inventory changes. ", disambig)),
      _association("SPickpocket",                QObject::tr("The default activation verb displayed when aiming at an NPC that can be pickpocketed.", disambig)),
      _association("sPipboyColor",               QObject::tr("Unused. The name of a display option in Fallout, which allows the player to change the color of the Pip-Boy and associated UI.", disambig)),
      _association("SPlaceMarkerUndiscovered",   QObject::tr("The dialog box shown to the player when they attempt to fast-travel to an undiscovered location. The player cannot fast-travel, but will be offered the option to place a custom waypoint at the location instead.", disambig)),
      _association("sPlayerLeavingBorderRegion", QObject::tr("Notification shown when the player's movement is stopped by the boundary of a border region.", disambig)),
      _association("sPoisonAlreadyPoisonedMessage", QObject::tr("Error message shown when the player attempts to apply poison to their current weapon when it is already poisoned.", disambig)),
      _association("sPoisonConfirmMessage",      QObject::tr("Text of a confirmation prompt shown to the player when they attempt to apply poison to their current weapon. The name of the weapon, and a question mark, will be appended to the text.", disambig)),
      _association("sPoisonNoWeaponMessage",     QObject::tr("Error message shown when the player attempts to apply poison to their current weapon, when they don't actually have a current weapon equipped.", disambig)),
      _association("sPoisonUnableToPoison",      QObject::tr("Error message shown when the player attempts to apply poison to their current weapon when they can't for an unspecified reason.", disambig)),
      _association("sPotionCreationFailed",      QObject::tr("Error message shown when the player tries and fails to brew a potion because the chosen ingredients have no effects in common.", disambig)),
      _association("sQuestFailed",               QObject::tr("Unused.", disambig)),
      _association("sRadioSignalLost",           QObject::tr("Unused. Notification shown when a Fallout player exits the broadcast range of a radio station. The format string parameter is the name of the radio station.", disambig)),
      _association("sRadioStationDiscovered",    QObject::tr("Unused. Notification shown when a Fallout player enters the broadcast range of a radio station. The format string parameter is the name of the radio station.", disambig)),
      _association("sRenameItem",                QObject::tr("The label for the \"Rename Item\" button or keybind in the enchanting menu.", disambig)),
      _association("sRewardXPIcon",              QObject::tr("Unused. A leftover from Oblivion's UI engine.", disambig)),
      _association("sRide",                      QObject::tr("The default activation verb displayed when aiming at a horse that can be ridden.", disambig)),
      _association("sSearch",                    QObject::tr("The default activation verb displayed when aiming at a container or corpse whose inventory can be opened, if taking items wouldn't be a crime. The criminal equivalent is sStealFrom.", disambig)),
      _association("sSingleDragonSoulCount",     QObject::tr("Text used to display the number of dragon souls that the player has, if it's one; the format string for the plural is sMultipleDragonSoulCount. The format string parameter is the number (integer) of souls.", disambig)),
      _association("sSneakCaution",              QObject::tr("Unused. HUD text from Fallout, displayed when the player is sneaking and enemies are searching for them.", disambig)),
      _association("sSneakDanger",               QObject::tr("Unused. HUD text from Fallout, displayed when the player is sneaking and enemies are actively attacking them.", disambig)),
      _association("sSneakDetected",             QObject::tr("Unused. HUD text from Fallout, displayed when the player is sneaking and is detected by non-hostile actors.", disambig)),
      _association("sSneakHidden",               QObject::tr("Unused. HUD text from Fallout, displayed when the player is sneaking and is undetected.", disambig)),
      _association("sSoulCaptured",              QObject::tr("Notification shown when an enemy that the player has previously soul-trapped dies, and one of the player's soul gems is filled.", disambig)),
      _association("sSoulGemTooSmall",           QObject::tr("Notification shown when an enemy that the player has previously soul-trapped dies, but the player doesn't have a soul gem large enough to hold their soul.", disambig)),
      _association("sSpeechChallengeFailure",    QObject::tr("Unused. Text from Fallout's dialogue menu, displayed when the player fails a speech check.", disambig)),
      _association("sSpeechChallengeSuccess",    QObject::tr("Unused. Text from Fallout's dialogue menu, displayed when the player passes a speech check.", disambig)),
      _association("sSpellAdded",                QObject::tr("Notification shown when the player learns a spell, whether from a spell book or from a non-silent AddSpell script call.", disambig)),
      _association("sStatsPerkConfirm",          QObject::tr("The text of a confirmation prompt shown to the player when they choose a perk to unlock.", disambig)),
      _association("sSteal",                     QObject::tr("The default activation verb displayed when aiming at an item or horse that can be stolen.", disambig)),
      _association("sStealFrom",                 QObject::tr("The default activation verb displayed when aiming at a container or corpse whose inventory can be opened, if taking items would be a crime. The legal equivalent is sSearch.", disambig)),
      _association("sTalk",                      QObject::tr("The default activation verb displayed when aiming at an NPC that can be spoken to.", disambig)),
      _association("sTweenDisabledMessage",      QObject::tr("Notification shown when the player attempts to open the tween menu (from which they can access the inventory, magic, map, and perk menus) when a script has disabled access to it. The default text tells the player that they cannot access these menus while they are transformed into a werewolf.", disambig)),
      _association("sVATSMessageNoAmmo",         QObject::tr("Unused. VATS HUD text from Fallout, indicating that the player does not have enough ammo for their desired attack.", disambig)),
      _association("sVATSMessageZeroChance",     QObject::tr("Unused. VATS HUD text from Fallout, indicating that the player won't be able to hit a targeted enemy.", disambig)),
      _association("sVDSGManual",                QObject::tr("Unused. Decorative text shown in Fallout's loading screens.", disambig)),
      _association("sVDSGPlate",                 QObject::tr("Unused. Decorative text shown in Fallout's loading screens.", disambig)),
      _association("sWeaponBreak",               QObject::tr("Unused. Notification shown when the player's equipped weapon breaks. Weapon and armor degradation did not appear in Skyrim.", disambig)),
      _association("sWhite",                     QObject::tr("Unused. A color option for Fallout's Pip-Boy and associated UI.", disambig)),
      //
      #pragma region Skyrim Special
         _association("sCantInstallModDependency", QObject::tr("A string from the game's built-in mod browser: an error message telling the user that they cannot install a mod because they don't have all of its dependencies installed.", disambig)),
         _association("sCantInstallModInvalid", QObject::tr("A string from the game's built-in mod browser: an error message telling the user that a mod is corrupt or invalid, cannot be used, and should be deleted.", disambig)),
         _association("sCantLoadControls", QObject::tr("An error message stating that the player's control options could not be loaded, and that the defaults will be used.", disambig)),
         _association("sCantLoadSettings", QObject::tr("An error message stating that the player's game options could not be loaded, and that the defaults will be used.", disambig)),
         _association("sChangedModsResetConfirm", QObject::tr("Confirmation dialog asking the player whether they want to reload the game after changing their mod list via the in-game mod browser.", disambig)),
         _association("sConfirmNewMods",       QObject::tr("Confirmation dialog for starting a new game when mods are enabled. Emphasizes that Xbox or Steam Achievements are disabled.", disambig)),
         _association("sConfirmNewMods_Orbis", QObject::tr("Confirmation dialog for starting a new game when mods are enabled. Emphasizes that PlayStation Trophies are disabled.", disambig)),
         _association("sDeleteAllModsConfirm",    QObject::tr("Confirmation dialog for deleting all installed mods via the game's built-in mod browser.", disambig)),
         _association("sDeleteLibraryModConfirm", QObject::tr("Confirmation dialog for deleting an installed mod via the game's built-in mod browser. Emphasizes that if the mod is not available on Bethesda.net, it will not be recoverable", disambig)),
         _association("sDeleteModConfirm",        QObject::tr("Confirmation dialog for deleting all installed mods via the game's built-in mod browser.", disambig)),
         _association("sGamepadDisconnectedMessage", QObject::tr("Text of a dialog box instructing the player to connect a gamepad to continue.", disambig)),
         _association("sGamepadDisconnectedTitle",   QObject::tr("Title of a dialog box instructing the player to connect a gamepad to continue.", disambig)),
         _association("sLoadVanillaSaveWithMods",       QObject::tr("Confirmation dialog for loading a non-modded save when mods are enabled. Emphasizes that Xbox or Steam Achievements are disabled.", disambig)),
         _association("sLoadVanillaSaveWithMods_Orbis", QObject::tr("Confirmation dialog for loading a non-modded save when mods are enabled. Emphasizes that PlayStation Trophies are disabled.", disambig)),
         //
         _association("sReportModCat_Explicit",      QObject::tr("A string from the game's built-in mod browser: a terms of service violation -- in this case, that the mod or associated messaging contains explicit content.", disambig)),
         _association("sReportModCat_General",       QObject::tr("A string from the game's built-in mod browser: a terms of service violation -- in this case, a catch-all category.", disambig)),
         _association("sReportModCat_Harassment",    QObject::tr("A string from the game's built-in mod browser: a terms of service violation -- in this case, that the mod or associated messaging is harassing someone.", disambig)),
         _association("sReportModCat_Impersonation", QObject::tr("A string from the game's built-in mod browser: a terms of service violation -- in this case, that the user is impersonating someone.", disambig)),
         _association("sReportModCat_PrivateInfo",   QObject::tr("A string from the game's built-in mod browser: a terms of service violation -- in this case, that the mod or associated messaging includes someone's private information.", disambig)),
         _association("sReportModCat_Profanity",     QObject::tr("A string from the game's built-in mod browser: a terms of service violation -- in this case, that the mod or associated messaging contains profanity.", disambig)),
         _association("sReportModCat_Racial",        QObject::tr("A string from the game's built-in mod browser: a terms of service violation -- in this case, that the mod or associated messaging contains racist content.", disambig)),
         _association("sReportModCat_Religious",     QObject::tr("A string from the game's built-in mod browser: a terms of service violation -- in this case, that the mod or associated messaging expresses anti-religious prejudice.", disambig)),
         _association("sReportModCat_Slander",       QObject::tr("A string from the game's built-in mod browser: a terms of service violation -- in this case, that the mod or associated messaging is slanderous.", disambig)),
         _association("sReportModCat_Spam",          QObject::tr("A string from the game's built-in mod browser: a terms of service violation -- in this case, that the mod or associated messaging is spam.", disambig)),
         _association("sReportModChooseCategory",    QObject::tr("A string from the game's built-in mod browser: the text of a dialog box asking the user what terms of service violation they wish to report a mod for.", disambig)),
         _association("sReportModConfirm",           QObject::tr("A string from the game's built-in mod browser: the confirmation dialog for reporting a mod that violates the terms of service.", disambig)),
      #pragma endregion
   };
}

extern QString get_game_setting_description(const char* name) {
   if (!name)
      return QString();
   auto length = strlen(name);
   if (length < 2)
      return QString();
   for (auto& entry : _associations)
      if (_strnicmp(name, entry.name, length) == 0)
         return entry.description;
   return QString();
}