not-in-category=true

[category]
sentinel=true
integer=5
integer-commented = 5 ; Here's why this should be 5
integer-with-garbage = 5 abc d 5
integer-float = 5.9

string=   abc   
quoted-string = "   abc   "
single-string = '   abc   '
ticked-string = `   abc   `
mismatched-string = "   abc   '
;'" ; dummy line to fix syntax highlighting in VS lol
string-commented = abc     ; Here's why this should be abc
quoted-string-with-padding = "   abc   "   
quoted-string-with-garbage = "   abc   "   def   
string-multiple = "   abc   "   def   "   
;'" ; dummy line to fix syntax highlighting in VS lol
string-backslash = "   abc   \"   def   "   
;'" ; dummy line to fix syntax highlighting in VS lol

[]
sentinel=true

[   padded-category   ]
sentinel=true

[---dashed-category]
sentinel=true

[;commented-category]
sentinel=true
;commented-sentinel=true
commented;sentinel=true

[category-trailing-garbage-a] ;abc
sentinel = true

[category-trailing-garbage-b] garbage=true
sentinel = true


[fallback-test-a]
[]
sentinel = true