#pragma once
#include <QDialog>
#include <QModelIndex>
#include "ui_worldinput_modifier_editor.h" // generated by Qt UIC

#include "editor/subsystems/worldinput2/enums/input_device_type.h"

class QAction;
class QItemSelection;

namespace dovahkit::subsystems::worldinput {
   class control_scheme_modifier;
   class input_sequence;
}

class DKWorldinputInputSequenceModel;

class WorldinputModifierEditDialog : public QDialog {
   Q_OBJECT;
   public:
      using input_device_type = dovahkit::subsystems::worldinput::input_device_type;
      using data_type = dovahkit::subsystems::worldinput::control_scheme_modifier;
      
   public:
      WorldinputModifierEditDialog(input_device_type, QWidget* parent = nullptr);

      void initializeFrom(const data_type&);
      void overwrite(data_type&) const;

   protected:
      Ui::WorldinputModifierEditDialog ui;
      //
      const input_device_type device_type;

      using input_sequence = dovahkit::subsystems::worldinput::input_sequence;

      const DKWorldinputInputSequenceModel* _getInputSequenceModel() const;
      DKWorldinputInputSequenceModel* _getInputSequenceModel() { return const_cast<DKWorldinputInputSequenceModel*>(std::as_const(*this)._getInputSequenceModel()); }

      QModelIndex _getFirstSeqSelection();
      const QItemSelection _getSeqSelection();
};