#pragma once
#include <QDialog>
#include <QModelIndex>
#include "ui_worldinput_bind_editor.h" // generated by Qt UIC

#include "editor/subsystems/worldedit/enums/axis3D.h"
#include "editor/subsystems/worldedit/enums/gizmo_mode.h"
#include "editor/subsystems/worldinput2/enums/button_press_type.h"
#include "editor/subsystems/worldinput2/enums/input_device_type.h"
#include "editor/subsystems/worldinput2/enums/optional_yn.h"
#include "editor/subsystems/worldinput2/enums/range_input_axes.h"
#include "editor/subsystems/worldinput2/enums/range_input_control.h"

class QAction;
class QItemSelection;

namespace dovahkit::subsystems::worldinput2 {
   class  control_scheme_action;
   class  input_sequence;
   struct raycast_requirement;
}

class DKWorldinputInputSequenceModel;

class WorldinputBindEditDialog : public QDialog {
   Q_OBJECT;
   public:
      using input_device_type = dovahkit::subsystems::worldinput2::input_device_type;
      using data_type = dovahkit::subsystems::worldinput2::control_scheme_action;
      
   public:
      WorldinputBindEditDialog(input_device_type, QWidget* parent = nullptr);

      void initializeFrom(const data_type&);
      void overwrite(data_type&) const;

   protected:
      Ui::WorldinputBindEditDialog ui;
      //
      const input_device_type device_type;
      struct {
         QAction* set_raycast_associated = nullptr;
      } _treeview_context_menu;
      QWidget* _tool_options_widget = nullptr;

      using axis3D     = dovahkit::subsystems::worldedit::axis3D;
      using gizmo_mode = dovahkit::subsystems::worldedit::gizmo_mode;

      using button_press_type   = dovahkit::subsystems::worldinput2::button_press_type;
      using optional_yn         = dovahkit::subsystems::worldinput2::optional_yn;
      using range_input_axes    = dovahkit::subsystems::worldinput2::range_input_axes;
      using range_input_control = dovahkit::subsystems::worldinput2::range_input_control;
      using raycast_requirement = dovahkit::subsystems::worldinput2::raycast_requirement;

      using input_sequence = dovahkit::subsystems::worldinput2::input_sequence;

      const DKWorldinputInputSequenceModel* _getInputSequenceModel() const;
      DKWorldinputInputSequenceModel* _getInputSequenceModel() { return const_cast<DKWorldinputInputSequenceModel*>(std::as_const(*this)._getInputSequenceModel()); }

      QModelIndex _getFirstSeqSelection();
      const QItemSelection _getSeqSelection();

      void _setUpToolOptionsUI(int tool_id);
};