#pragma once
#include <QDialog>
#include <QModelIndex>
#include "ui_worldinput_condition_editor.h" // generated by Qt UIC
#include "editor/subsystems/worldinput/condition_set.h"

class QAction;
class QItemSelection;

namespace dovahkit::subsystems::worldinput {
   class control_scheme_condition;
}

class DKWorldinputInputSequenceModel;

class WorldinputConditionEditDialog : public QDialog {
   Q_OBJECT;
   public:
      using data_type = dovahkit::subsystems::worldinput::condition_set;
      using node_type = dovahkit::subsystems::worldinput::control_scheme_condition;
      
   public:
      WorldinputConditionEditDialog(QWidget* parent = nullptr);

      void initializeFrom(const node_type&);
      void overwrite(node_type&) const;

   protected:
      Ui::WorldinputConditionEditDialog ui;
      data_type _data;

      void _update_selection_count_constraint();
};