#pragma once
#include <QDialog>
#include "ui_worldinput_bind_editor.h" // generated by Qt UIC

class WorldinputBindEditDialog : public QDialog {
   Q_OBJECT;
   public:
      WorldinputBindEditDialog(QWidget* parent = nullptr);

   protected:
      Ui::WorldinputBindEditDialog ui;
};