#include "conditions.h"

ConditionFunction conditionFunctions[] = {
   ConditionFunction(  0, "GetWantBlocking",   ""),
   ConditionFunction(  1, "GetDistance",       "Returns the distance between this reference and another reference.", ConditionParamType::ObjectReference),
   ConditionFunction(  2, ConditionFunction::dummy),
   ConditionFunction(  3, ConditionFunction::dummy),
   ConditionFunction(  4, ConditionFunction::dummy),
   ConditionFunction(  5, "GetLocked",         "Returns 1 if this reference is a locked door or container, or 0 otherwise."),
   ConditionFunction(  6, "GetPos",            "Returns this reference's position along the given axis.", ConditionParamType::Axis),
   ConditionFunction(  7, ConditionFunction::dummy),
   ConditionFunction(  8, "GetAngle",          "Returns this reference's rotation along the given axis.", ConditionParamType::Axis),
   ConditionFunction(  9, ConditionFunction::dummy),
   ConditionFunction( 10, "GetStartingPos",    "Returns this reference's starting position along the given axis.", ConditionParamType::Axis),
   ConditionFunction( 11, "GetStartingAngle",  "Returns this reference's starting position along the given axis.", ConditionParamType::Axis),
   ConditionFunction( 12, "GetSecondsPassed",  ""),
   ConditionFunction( 13, ConditionFunction::dummy),
   ConditionFunction( 14, "GetActorValue",     "Returns the current value of the specified ActorValue.", ConditionParamType::ActorValue),
   ConditionFunction( 15, ConditionFunction::dummy),
   ConditionFunction( 16, ConditionFunction::dummy),
   ConditionFunction( 17, ConditionFunction::dummy),
   ConditionFunction( 18, "GetCurrentTime",    ""),
   ConditionFunction( 19, ConditionFunction::dummy),
   ConditionFunction( 20, ConditionFunction::dummy),
   ConditionFunction( 21, ConditionFunction::dummy),
   ConditionFunction( 22, ConditionFunction::dummy),
   ConditionFunction( 23, ConditionFunction::dummy),
   ConditionFunction( 24, "GetScale",          "Returns this reference's scale."),
   ConditionFunction( 25, "IsMoving",          ""),
   ConditionFunction( 26, "IsTurning",         ""),
   ConditionFunction( 27, "GetLineOfSight",    "", ConditionParamType::ObjectReference),
   ConditionFunction( 28, ConditionFunction::dummy),
   ConditionFunction( 29, ConditionFunction::dummy),
   ConditionFunction( 30, ConditionFunction::dummy),
   ConditionFunction( 31, ConditionFunction::dummy),
   ConditionFunction( 32, "GetInSameCell",     "Returns 1 if this reference is in the same cell as the specified reference, or 0 otherwise.", ConditionParamType::ObjectReference),
   ConditionFunction( 33, ConditionFunction::dummy),
   ConditionFunction( 34, ConditionFunction::dummy),
   ConditionFunction( 35, "GetDisabled",       "Returns 1 if this reference is disabled, or 0 otherwise."),
   ConditionFunction( 36, "MenuMode",          "", ConditionParamType::Integer),
   ConditionFunction( 37, ConditionFunction::dummy),
   ConditionFunction( 38, ConditionFunction::dummy),
   ConditionFunction( 39, "GetDisease",        ""),
   ConditionFunction( 40, ConditionFunction::dummy),
   ConditionFunction( 41, "GetClothingValue",  ""),
   ConditionFunction( 42, "SameFaction",       "Returns 1 if this reference is in the same faction as the specified actor, or 0 otherwise.", ConditionParamType::Actor),
   ConditionFunction( 43, "SameRace",          "Returns 1 if this reference is of the same race as the specified actor, or 0 otherwise.", ConditionParamType::Actor),
   ConditionFunction( 44, "SameSex",           "Returns 1 if this reference is of the same sex as the specified actor, or 0 otherwise.", ConditionParamType::Actor),
   ConditionFunction( 45, "GetDetected",       "", ConditionParamType::Actor),
   ConditionFunction( 46, "GetDead",           ""),
   ConditionFunction( 47, "GetItemCount",      "Returns how many of the specified form this reference has in its inventory.", ConditionParamType::InventoryItem),
   ConditionFunction( 48, "GetGold",           "Returns how much gold this reference is carrying."),
   ConditionFunction( 49, "GetSleeping",       ""),
   ConditionFunction( 50, "GetTalkedToPC",     ""),
   ConditionFunction( 51, ConditionFunction::dummy),
   ConditionFunction( 52, ConditionFunction::dummy),
   ConditionFunction( 53, "GetScriptVariable",  "", ConditionParamType::ObjectReference, ConditionParamType::ScriptVariableIndex),
   ConditionFunction( 54, ConditionFunction::dummy),
   ConditionFunction( 55, ConditionFunction::dummy),
   ConditionFunction( 56, "GetQuestRunning",    "Returns 1 if the specified quest is running, or 0 otherwise.", ConditionParamType::Quest),
   ConditionFunction( 57, ConditionFunction::dummy),
   ConditionFunction( 58, "GetStage",           "Returns the specified quest's current stage number.", ConditionParamType::Quest),
   ConditionFunction( 59, "GetStageDone",       "Returns 1 if the specified quest stage is complete, or 0 otherwise.", ConditionParamType::Quest, ConditionParamType::QuestStage),
   ConditionFunction( 60, "GetFactionRankDifference", "", ConditionParamType::Faction, ConditionParamType::Actor),
   ConditionFunction( 61, "GetAlarmed",         ""),
   ConditionFunction( 62, "IsRaining",          "Returns 1 if the current weather is rainy, or 0 otherwise."),
   ConditionFunction( 63, "GetAttacked",        ""),
   ConditionFunction( 64, "GetIsCreature",      ""),
   ConditionFunction( 65, "GetLockLevel",       ""),
   ConditionFunction( 66, "GetShouldAttack",    "", ConditionParamType::Actor),
   ConditionFunction( 67, "GetInCell",          "Returns 1 if this reference is in the specified cell, or 0 otherwise.", ConditionParamType::Cell),
   ConditionFunction( 68, "GetIsClass",         "Returns 1 if this actor is of the specified class, or 0 otherwise.", ConditionParamType::Class),
   ConditionFunction( 69, "GetIsRace",          "Returns 1 if this actor is of the specified race, or 0 otherwise.",  ConditionParamType::Race),
   ConditionFunction( 70, "GetIsSex",           "Returns 1 if this actor is of the specified sex, or 0 otherwise.",   ConditionParamType::Sex),
   ConditionFunction( 71, "GetInFaction",       "", ConditionParamType::Faction),
   ConditionFunction( 72, "GetIsID",            "", ConditionParamType::BaseForm),
   ConditionFunction( 73, "GetFactionRank",     "", ConditionParamType::Faction),
   ConditionFunction( 74, "GetGlobalValue",     "Returns the value of the specified Global.", ConditionParamType::Global),
   ConditionFunction( 75, "IsSnowing",          "Returns 1 if the current weather is snowy, or 0 otherwise."),
   ConditionFunction( 76, ConditionFunction::dummy),
   ConditionFunction( 77, "GetRandomPercent",   "Returns a random number between 0 and 100, inclusive."),
   ConditionFunction( 78, ConditionFunction::dummy),
   ConditionFunction( 79, "GetQuestVariable",   "", ConditionParamType::Quest, ConditionParamType::ScriptVariableIndex),
   ConditionFunction( 80, "GetLevel",           "Returns this actor's level."),
   ConditionFunction( 81, "IsRotating",         ""),
   ConditionFunction( 82, ConditionFunction::dummy),
   ConditionFunction( 83, ConditionFunction::dummy),
   ConditionFunction( 84, "GetDeadCount",       "Returns the number of times this character has died.", ConditionParamType::ActorBase),
   ConditionFunction( 85, ConditionFunction::dummy),
   ConditionFunction( 86, ConditionFunction::dummy),
   ConditionFunction( 87, ConditionFunction::dummy),
   ConditionFunction( 88, ConditionFunction::dummy),
   ConditionFunction( 89, ConditionFunction::dummy),
   ConditionFunction( 90, ConditionFunction::dummy),
   ConditionFunction( 91, "GetIsAlerted", ""),
   ConditionFunction( 92, ConditionFunction::dummy),
   ConditionFunction( 93, ConditionFunction::dummy),
   ConditionFunction( 94, ConditionFunction::dummy),
   ConditionFunction( 95, ConditionFunction::dummy),
   ConditionFunction( 96, ConditionFunction::dummy),
   ConditionFunction( 97, ConditionFunction::dummy),
   ConditionFunction( 98, "GetPlayerControlsDisabled", "", ConditionParamType::Integer, ConditionParamType::Integer),
   ConditionFunction( 99, "GetHeadingAngle",    "", ConditionParamType::ObjectReference),
   ConditionFunction(100, ConditionFunction::dummy),
   ConditionFunction(101, "IsWeaponMagicOut",   ""),
   ConditionFunction(102, "IsTorchOut",         ""),
   ConditionFunction(103, "IsShieldOut",        ""),
   ConditionFunction(104, ConditionFunction::dummy),
   ConditionFunction(105, ConditionFunction::dummy),
   ConditionFunction(106, "IsFacingUp",         ""),
   ConditionFunction(107, "GetKnockedState",    ""),
   ConditionFunction(108, "GetWeaponAnimType",  ""),
   //
   // ...FINISH ME!!!
   //
};