#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include "Form.h"
#include "_common.h"
#include "components/bounds.h"
#include "components/extra_data.h"
#include "components/interior_lighting.h"
#include "components/papyrus.h"
#include "../../helpers/vector3.h"

namespace dovah::loaded_forms {
   class Cell : public Form {
      #include "impl/form_subclass_components.txt"
      public:
         static constexpr form_type_t form_type = form_type::cell;
         Cell(const constructor_params& c) : Form(form_type, c) {};

         struct form_flag : public Form::form_flag {
            enum : uint32_t {
               persistent = 0x00000400,
               off_limits = 0x00020000,
               cant_wait  = 0x00080000,
            };
         };

         struct cell_flag {
            cell_flag() = delete;
            enum {
               interior              = 0x0001,
               has_water             = 0x0002, // TESV.exe forces this to (true) on load if the (interior) flag is not set
               cant_travel_from_here = 0x0004,
               no_lod_water          = 0x0008,
               public_area           = 0x0020,
               hand_changed          = 0x0040,
               show_sky              = 0x0080,
               use_sky_lighting      = 0x0100,
            };
         };
         struct land_flag {
            land_flag() = delete;
            enum {
               force_hide_quad_1 = 0x01,
               force_hide_quad_2 = 0x02,
               force_hide_quad_3 = 0x04,
               force_hide_quad_4 = 0x08,
            };
         };

         struct max_height_data_t {
            float offset;
            std::array<std::array<int8_t, 32>, 32> grid;
            bool  present = false;
            //
            void clear() {
               this->present = false;
            }
         };
         struct occlusion_data_t {
            std::vector<uint8_t> bytes;
            bool present = false;
            //
            void clear() {
               this->bytes.clear();
               this->present = false;
            }
         };

         localized_string name; // FULL
         uint16_t cell_flags = 0; // DATA
         uint32_t land_flags = 0; // XCLC
         components::extra_data_list extra_data;
         struct {
            components::interior_lighting lighting; // XCLL (LNAM overrides the inherit flags specifically)
            form_reference_t lighting_template; // LTMP
         } interior;
         struct {
            occlusion_data_t  occlusion_data;  // TVDT ("Terrain Visibility Data?")
            max_height_data_t max_height_data; // MHDT
         } exterior;
         struct {
            float       height = 0.0F; // XCLW
            std::string noise_texture; // XNAM
         } water;
         //
         // Additional content that the game is theoretically capable of identifying, but 
         // that is never generated by official tools:
         //
         bool has_object_bounds = false;
         components::object_bounds object_bounds; // OBND. recognized, but probably discarded at run-time.
         components::papyrus_attachment_data script_data; // VMAD

         void load(tes_record_reader&, load_order_interfaces::form_load& intfc);
         static void generate_use_info(tes_record_reader&, form_stub_use_info_builder&);
         //
         virtual void setup(const file_load_order&) noexcept override;
         virtual bool would_bethesda_compress() const noexcept override;
         //
      protected:
         virtual bool _clone_impl(Form* out) const noexcept override;
         virtual bool _save_impl(tes_file_writing::record& record, load_order_interfaces::form_save& intfc) override;
         virtual void _clear_impl() noexcept override;
         virtual void _sever_outbound_references_impl(form_stub& other) noexcept override;
   };
}